### ISSUE TITLE
As a FS employee I would like to see the applications submitted in SUDS, so that I don't have to enter it in manually (move to Prod SUDS)

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-open-forest-platform#149]
## Notes
We are currently working with DEV suds, and will want to move to NRM/SUDS Prod before we go live.

## Acceptance Criteria
- [ ]

## Tasks
- [ ] Move VCAP service endpoint to prod SUDS API
- [ ] Ask SUDS devs about process for getting into production
- [ ] More tasks TBD

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Can you say more about what this means? Does this mean that the end users wants to receive verification that the app was entered into SUDS? @lauraGgit

**Comment by lauraGgit** [comment]
Ah, this is cryptically described in the Tasks. We are currently working with DEV suds, and will want to move to NRM/SUDS Prod before we go live.

**Comment by hannahkane** [comment]
Ah, got it! @msadakFS - does that make sense to you?

I updated the first comment to reflect this.

**Comment by msadakFS** [comment]
@hannahkane Yes, that makes perfect sense

**Comment by lauraGgit** [comment]
Ok, further testing with staging and an accepted application. Staging/Prod are returning the same errors for a random control number submitted. This suggests that it is enabled in production but cannot fully verify until an actual application is submitted in SUDS. Moving to PO acceptance.

**Comment by ASprinkle** [comment]
LG verified. Final end to end needed.
