### ISSUE TITLE
As a SU applicant or admin, I want to be able to receive/send from a FS email so that the email is seen as official

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-open-forest-platform#151]
## Notes
Will leverage the USDA SMTP relay.

## Acceptance Criteria
- [ ] sends email from usda.gov email address.

## Tasks
- [X] Change VCAP endpoint to usda smtp
- [X] update site architecture diagrams
- [X] notifiy paul of changed diagrams
- [X] Send email to Tim about connection refused.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Currently waiting on ok, that our IPs are in.

**Comment by lauraGgit** [comment]
enable app to work without the "username" credential set

**Comment by lauraGgit** [comment]
Initial test- ERR Connection refused.

**Comment by lauraGgit** [comment]
From a `traceroute` this looks like our request is getting caught in their network firewall rules.

**Comment by hannahkane** [comment]
Are we able to test this yet?

**Comment by lauraGgit** [comment]
They are now saying end of August for this. I believe for our BETA we could still use the existing email functionality.

**Comment by lauraGgit** [comment]
Go live is next week. Moving back to blocked.

**Comment by lauraGgit** [comment]
This may be because of the port we are providing - reviewing previous emails.

**Comment by lauraGgit** [comment]
Currently sending from Aaron's successfully - now we need a generic email address.

**Comment by msadakFS** [comment]
I tested and was receiving an email from Aaron's email
