### ISSUE TITLE
As a user, I want to be able to reliably access the app, so that I can achieve my goals (sticky sessions)

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-open-forest-platform#154]
## Notes
In order to support multiple instances, we have to refactor our authorization code to be more stateless. The link below hightlights how to do this on a node application.

## Acceptance Criteria
- [ ] I can login into an application, regardless of which instance I am hitting

## Tasks
- [X] Research whether to support authentication with multiple instances in production; should the application use sticky sessions
- [x] Update to shared cookie key
- [x] Update API and server and frontend manifest to allow for multiple instances

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
I think we want to look back into going from cookies back to JWT - https://medium.com/front-end-hacking/learn-using-jwt-with-passport-authentication-9761539c4314.

At one point, during the development of the intake module this was started, but I think that was missing https://github.com/flexion/fs-intake-module/pull/939/files - it looks like that didn't implement a `passport-jwt` authorization strategy for other routes.

**Comment by msadakFS** [comment]
@lauraGgit Can explain this issue? For instance, what is sticky sessions?

**Comment by lauraGgit** [comment]
@msadakFS I update the notes on this a bit. This issue is about some refactoring we have to do in order to better support our application in production when we will have multiple instances of the production apps running in the cloud.

**Comment by lauraGgit** [comment]
for angular task: https://ryanchenkie.com/angular-authentication-using-the-http-client-and-http-interceptors

**Comment by lauraGgit** [comment]
@msadakFS moving this past PO review, because it would be rather hard to actually test this.
