### ISSUE TITLE
"Switch is flipped" on Production on 11/16

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-open-forest-platform#160]
As a public user, I want to be able to access the site, so that I can submit an application.

## Notes
likely won't do this until soft launch date

## Acceptance Criteria
- [ ] A member of the public can access openforest.fs.usda.gov without a password.

## Tasks
- [ ] Remove basic auth just on master site
- [x] Modify build process to support branch-dependent auth
- [x]  Update cf-ignore to be branch-dependent within Circle
- [x] Production checklist

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
This is now there but for flipping the switch. Dev site credentials have also been updated seen channel.

**Comment by msadakFS** [comment]
Blocked until we get ATO

**Comment by lauraGgit** [comment]
This is no longer blocked! 🎉

**Comment by ASprinkle** [comment]
Refine in consideration with #418

**Comment by ASprinkle** [comment]
Notes from refinement 11/13 - leave special uses side the way it is (/mbs) - reevaluate if SU applications are coming through.

**Comment by lauraGgit** [comment]
Went through the production checklist to verify what was relevant to Christmas Trees
