### ISSUE TITLE
As a user, I should recognize the app by its name "Open Forest," so that I can easily find it and talk about it

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-open-forest-platform#183]
## Notes
Open Forest documented/branded on website and emails

## Acceptance Criteria
- [X] Product name, "Open Forest," should be visible and obvious to users on any page of the site and in any transactional comms 
- [X] ePermit should not be mentioned anywhere on the site or in any transactional comms

## Tasks
- [x] Search Engine Optimization for Open Forest Site
       - [ ]  Header
       - [ ]  Metadata
       - [ ]  Keywords

- [x] Place Open Forest on application website. (refer to Anne's list)
        - [X] Header
        - [X] Email
        - [X] Title (Xmas Tees still says ePermit)

Update readme to replace ePermit with Open Forest
## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@annepetersen and Marcus will take a look at options for branding Open Forest

**Comment by msadakFS** [comment]
Open Forest branding on website and emails

**Comment by msadakFS** [comment]
https://www.recreation.gov/ provide a pretty good example to follow. Would designing a logo be appropriate? Everything else seems to have one. Rec.gov says "Explore Your America" under their logo. "Access Your Forest" for Open Forest??? I know creating logos and other branding can get tricky in the USDA so not quite sure of the restraints.

**Comment by hannahkane** [comment]
I believe @aaronburk has said no to creating a logo in the past. @aaronburk, is that still the case?

**Comment by aaronburk** [comment]
That is correct the feedback I have received in the past is USFS Shield and USDA logo only.

**Comment by aaronburk** [comment]
Marcus does bring up a good point about Rec.gov however at this time we can move forward with with USFS Shield and USDA Logo

**Comment by msadakFS** [comment]
@hannahkane @aaronburk    Thoughts on iceboxing this issue? Do we have a designer that can provide feedback? Is it critical to have "Open Forest" on the application site?

**Comment by lauraGgit** [comment]
also likely we want to include @annepetersen on this conversation as well.

**Comment by annepetersen** [comment]
I would advise using Open Forest or some other name for the service if we can. Users will not know or recognize or remember the service if it’s just named “permitting” or if it uses some other internal terminology. It’s also much more Googlable/searchable that way. Spreading the word also becomes much easier with a distinct name. Plus then people can more easily connect the site, emails from the system, and the printed permits if there’s a consistent name on each.

So: naming it grants a definite benefit in usability, consistency, recognizability and marketing. This doesn’t mean a logo is required, just public and consistent terminology.

**Comment by msadakFS** [comment]
What needs to change as far as code to make more efficient google search?
What Forest websites (i.e. MBS https://www.fs.usda.gov/main/mbs/passes-permits , etc.)  need to be updated? Who updates them?
Do we simply place "Welcome to Open Forest" on top of the website? 

Who makes the design decisions above?

**Comment by annepetersen** [comment]
Your first question isn't a short answer: it's a whole field called SEO, though SEO covers content as well as code. A primer can be found here: https://blog.hubspot.com/marketing/seo (jump down to "Three Core Components of a Strong SEO Strategy"). 

The good news is that your site will be given more credibility by search engines just by being a .gov.

The bad news is that Open Forests is a product in the marketplace already: https://openforests.com/ We can hope that pluralization might differentiate us, but should know there may be some confusion.

We'd need to take a pass to assess which sites need to be updated, and let whoever the content editor is know what needs to happen.

Not necessarily "Welcome to," but definitely putting Open Forest at the top of the website would help. Having the name in headers is key to SEO.

I can advise on these design decisions, but certainly the appropriate stakeholders should weigh in.

**Comment by msadakFS** [comment]
Open Forest isn't plural. There is also a openforest.net.

**Comment by msadakFS** [comment]
Who are the appropriate stakeholders? What I need assistance with is defining all the places where Open Forest needs to be instaniated. Is that something you can put together @annepetersen ?

**Comment by msadakFS** [comment]
I'll see if I can track down those content editors. Those vary by Region/Unit. 
Who can we assign the SEO tasks too? Is that something you can do @annepetersen ?

**Comment by annepetersen** [comment]
They'll vary: some I can take, some may need @lauraGgit, etc. Content = me or @coreycaitlin, code = @lauraGgit, generally.

I should also state for the record that we'd need to do much of this whether or not we were using the new name. For example, the assessment of where these links exist and should be updated would need to be done regardless.

**Comment by msadakFS** [comment]
This issue would be much clearer to me if I had a task list that specifies all the activities that need to be executed to complete both branding and search-ability. I will schedule a call this week to dig in a bit deeper.

**Comment by msadakFS** [comment]
Colton Whitworth is the MBS NF contact for changing the external facing MBS site(s). Colton works in their Public Affairs shop

**Comment by lauraGgit** [comment]
I'm going to start on the title service, because I think i know where all those would be.

**Comment by lauraGgit** [comment]
Added Title to all Special use, Error Pages, and Xmas home. Need further Xmas pages.

@annepetersen Email template are here:
https://github.com/18F/fs-open-forest-platform/tree/dev/server/src/email/templates/christmas-trees
https://github.com/18F/fs-open-forest-platform/tree/dev/server/src/email/templates/special-use-common

**Comment by lauraGgit** [comment]
The wrapper for the EMAIL template
https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/email/assets/html-template.es6

**Comment by ASprinkle** [comment]
PO reviewed on sites.  
"USFS e-permits" appears on the credit card statement. Should this be changed to "Open Forest"?Acceptance criteria says "ePermit should not be mentioned anywhere on the site or in any transactional comms"
