### ISSUE TITLE
As a user, I would like to make sure all season dates have time zones, so that I know exactly when things start.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#220]
## Notes
Newer versions of moment-js-timezone throw an error when no timezone is passed to a moment js file. Currently we do not pass timezone in all the tests in the frontend unit tests need to be updated.
We are currently using the previous version of moment timezone and this change will allow to ensure we are using the latest version

## Acceptance Criteria
- [ ] The tests pass with the most up to date version of moment js timezone.

## Tasks
- [ ] Identify dates without associated timezone and modify to include the timezone
- [ ] Ensure  the change is also reflected in any associated tests
- [ ] Update the moment timezone javascript library

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
We might want to take care of this since we have the time.

**Comment by lauraGgit** [comment]
The breaking change was fixed, so I cleaned up dependencies and bumped up the version.
