### ISSUE TITLE
As a user, I should be able to pay for Christmas Tree permits using pay.gov

### ISSUE THREAD

**Issue by hannahkane** [18F/fs-open-forest-platform#241]
## Notes
mostly switching over VCAPS for prod instance and testing payment in prod.

## Acceptance Criteria
- [ ] can use a real credit card to buy a permit and that money gets back to the forest

## Tasks
 - [x] swap out VCAP for prod pay.gov environment on open forest prod
- [ ] follow up with USFS CFO to confirm that payments went to FMMI

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by hannahkane** [comment]
Note: I'm filing this issue now so that we can retire the production checklist, but it is outside the scope of the current work to get the Special Use pilot into production.

**Comment by msadakFS** [comment]
Blocked until we request pay.gov in production

**Comment by msadakFS** [comment]
Production Pay.gov request has been made to Daniel Cha. POSS Central Office in Prod will not be until end of Sept.

**Comment by msadakFS** [comment]
Waiting for Pay.gov IAA signing by all parties

**Comment by lauraGgit** [comment]
@msadakFS that conversation was for login.gov, pay.gov ISA i think is under control.

**Comment by msadakFS** [comment]
Blocked until we get prod. url.

**Comment by msadakFS** [comment]
Waiting on credentials from D. Cha

**Comment by lauraGgit** [comment]
Correction, we have this info- moving it out of unblocked.

**Comment by lauraGgit** [comment]
Debugging cert issues.

**Comment by lauraGgit** [comment]
Cert issues resolved, but being rejected by policy failure. Sent off email to Treasury/CFO policy folks to confer on status.

**Comment by lauraGgit** [comment]
tldr: it was a combination on
1. poor documentation on our end on how to convert the certificate into a usable format for us (will update)
2. a weird config error on their end
3. having the wrong client url in the system

So still need to update documentation and then will consider this done.

**Comment by lauraGgit** [comment]
Moving past PO viewable, because not on staging and confirmed now on production.

**Comment by lauraGgit** [comment]
However per the acceptance criteria, this is blocked until next week when we can buy a permit!

**Comment by aaronburk** [comment]
Thanks Laura.  Let me know if there is anything I can do.
