### ISSUE TITLE
As a User I can easily find and navigate site so that I can apply for the permit type and forest of my choosing

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-open-forest-platform#263]
## Notes
Change routing to to openforest.fs.usda.gov/mbs/ and then have each permit type being a subroute of that, e.g. openforest.fs.usda.gov/arp/christmas

Special use admin routes should be changed to admin/mbs/special-use-applications
Admin Xmas tree routes, would not need to change.
User/applications would not need to change as they would be across forests

## Acceptance Criteria
- [ ] Discover-ability and entry points from NF pages are established
- [ ] Create a visualization that delineates the IA and content of each page
- [ ] User has a path to landing site and can easily navigate to other forests and/or other permit types

## Tasks
- [ ] define the UX and IA
                * what content would live on openforest.fs.usda.gov/christmas-trees
                * what content would live on openforest.fs.usda.gov/arp
                * how would breadcrumbs work
- [ ] add and design a page for something at the root /
- [ ] change /christmas-trees/forests to just christmas-trees https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L212
- [ ] update the ForestResolver to be a prefix rather than a child https://github.com/18F/fs-permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L228
- [ ] change to ':id/christmas-trees/applications/permits/:permitId', https://github.com/18F/fs- 
permit-platform/blob/dev/frontend/src/app/app-routing.module.ts#L273
- [ ] lines 284-295 stay the same
- [ ] Update automated tests
- [ ] Update breadcrumbs 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Related to https://github.com/18F/fs-permit-platform/issues/200#issuecomment-403562566

**Comment by msadakFS** [comment]
@hannahkane Please review to see if I am on track with this new issues based on our "Check In" call discussion.

**Comment by msadakFS** [comment]
Need to follow-up with @annepetersen

**Comment by msadakFS** [comment]
Not critical for production

**Comment by ASprinkle** [comment]
Refinement meeting decision to close - redundant with tasks already completed. #363
