### ISSUE TITLE
Feedback form

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-open-forest-platform#316]
As a Product Owner/Manager, I should be able to get feedback from users to evaluate customer satisfaction or value proposition is met

## Notes
Customers can provide feedback on the usability of Open Forest

## Acceptance Criteria
- [ ] Customer can report bugs or share feedback and feature requests

## Tasks
- [ ] Look at alternatives and choose "survey" style asking for feedback.
- [ ] Identify where is an effective location to ask for "survey" feedback.
- [ ] Develop google forms (or format for gathering feedback).
- [ ] Develop content (where it belongs on page (and within process) for all permit types)
- [ ] Implement 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
Should tie into customer satisfaction metric on the product roadmap

**Comment by msadakFS** [comment]
Example questions:
1. What do you like most about the Open Forest product?
2. What changes would most improve our new product?
3. Overall, are you satisfied with your experience using our new product? (Very satisfied, somewhat satisfied, neither satisfied nor dissatisfied, somewhat dissatisfied, very dissatisfied)
4. How likely are you to use Open Forest again? (Very likely, somewhat likely, neither likely or not at all, somewhat unlikely, not likely)

**Comment by msadakFS** [comment]
Blocked until Researcher provides guidance and MBS staff can provide input.

**Comment by msadakFS** [comment]
Not a priority for production

**Comment by suprenant** [comment]
From our strategy session earlier today, I'm moving this to the sprint backlog so we can get it done in time for the pilot.

**Comment by ASprinkle** [comment]
Some questions to answer as we think about this one, specific to building something (google form is mentioned in tasks) that is targeted toward the forest visitor/external:

 - how do we solicit the feedback from the forest visitor who uses Open Forest to get a permit?
 - how do we solicit feedback from the forest visitor to comes to the site, but leaves without purchasing?

The FS already has a contract with FORSEE in some areas for customer feedback surveys. Usually when I encounter these, I close them quickly so that I can get back to what I wanted to accomplish. I am not sure how informative this method would be. 

Soliciting feedback from internal FS staff at pilot forests and regions may be easier and completed by way of meetings/conversations. I have scheduled weekly check-ins during the pilot, and scheduled feedback sessions for after the pilot. We can do more to structure the questions around these feedback sessions. - Internal Feedback/customer satisfaction may be a different card.

**Comment by annepetersen** [comment]
Agreed there needs to be a balance between it being intrusive and it being noticeable/available. FORSEE is way too far on the intrusive end, in my opinion.

Here's a decent article with an overview of options, both products and things we could implement (like Google Forms, feedback.js, etc.): https://mopinion.com/31-website-feedback-tools-an-overview-and-comparison/

You'll note there that with most products that aren't a pop-up or splash of some sort, the feedback button/option tends to appear at bottom right or as a tab-like button at the far right middle of the visible screen. 

Funnily enough, one of the products mentioned has itself implemented a simple link in their footer that says "Give Us Feedback!" which would be easy enough for us to do. https://pulseinsights.com/

**Comment by cmaczo** [comment]
Hello from 🇨🇦 and the distant past! I happened on this issue while looking for something else, and just wanted to offer a couple comments.

Responses to a survey may not be a good measure of "customer satisfaction or [whether the] value proposition is met." As @ASprinkle points out, you won't get people who leave, and you may not get satisfied people who head off quickly with their permit. 

A survey will capture people who have something they'd particularly like to say. That may be useful for catching bugs or gathering new ideas. But it won't be a measure of the overall customer satisfaction.

To get at overall customer satisfaction, you might want to consider looking a panel of metrics like:
- A single-item question for permit recipients at the end of the process, on a normed scale like the [SEQ](https://measuringu.com/seq10/).
- A thumbs-up/thumbs-down button on various pages of the process
- The percentage of people who make it through the permit approval process, via Google Analytics
- Ongoing intercept usability testing with tools like Ethn.io or Hotjar

**Comment by suprenant** [comment]
Thanks for your helpful comments @cmaczo – what a nice and welcome surprise to hear from you. We are considering what you outline here. 

Hope all is well up north! :)

**Comment by ASprinkle** [comment]
suggestion is to utilize the email available and keep a close eye on analytics.
