### ISSUE TITLE
Buy a  Christmas tree dropdown menu issue

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-open-forest-platform#328]
## Notes
When a user goes the the homepage and clicks on the drop down to select a forest in the 'Buy a Christmas tree"  box Arapaho Roosevelt is in bold and others are not.  This implies to a user the others may be "grayed out" therefor not delectable.   Either they should all be bold or not bold.
## Acceptance Criteria
- [ Forest to select need to be a consistent shade]

## Tasks
[https://app.zenhub.com/files/88538878/685feb99-2076-4d44-af2b-058180f4a478/download](https://app.zenhub.com/files/88538878/685feb99-2076-4d44-af2b-058180f4a478/download)

- [ ] Need acceptance criteria for accessibility. 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
![image](https://user-images.githubusercontent.com/39954421/44533353-fa674580-a6ba-11e8-9864-e8ff5e992fc3.png)

**Comment by lauraGgit** [comment]
@annepetersen ok, it looks like that a default `Select` option is ok per the [USWDS](https://designsystem.digital.gov/components/form-controls/) do you think that `Select a forest` is the appropriate copy for this?
