### ISSUE TITLE
As a user I would like my application reviewed within 48 hours

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-open-forest-platform#353]
## Notes
On the email, it states "1.	Your application will be reviewed by our staff within 48 hours."

What if I apply Friday afternoon on a long holiday weekend? Should the email state within 48 hours or 2 business days?

## Acceptance Criteria
- [ ] Users are notified that their application will be reviewed within 48 hours or 2 business days.

## Tasks
- [ ] Update estimate on email
- [ ] Search code base for all instances of "48 hours"
- [ ] Update code base 

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by msadakFS** [comment]
@lauraGgit I assume the estimate is pretty low on this issue?

**Comment by lauraGgit** [comment]
Given that we never discussed this as a group, i think it should stay in the back log.

**Comment by ASprinkle** [comment]
PO reviewed.
