### ISSUE TITLE
As a user, I would like to easily find the Open Forest Christmas Tree site

### ISSUE THREAD

**Issue by msadakFS** [18F/fs-open-forest-platform#363]
## Notes
Related to issue #263 

Change Open Forest homepage to the Christmas Tree module

## Acceptance Criteria
- [x] Change Open Forest homepage so that it goes directly to the Christmas Tree module as this will be released first

## Tasks
- [ ] Open Forest homepage routed to Christmas Tree site
- [ ] Change MBS site to \MBS
- [ ] Change Wiki references

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by aaronburk** [comment]
I approve moving forward

**Comment by ASprinkle** [comment]
PO reviewed.
