### ISSUE TITLE
[Spike] As someone with a slow browser, I'd like the site to load faster (via Angular 7 upgrade)

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#382]
## Notes
At one point @hursey013 and I started down the path of upgrading to Angular 7 (we're on 5) and ran into some stumbling blocks - in part because it forced us into pre-compliation for production - which would make the site a lot faster, but some of the plugins we use aren't in good shape for that yet.

Will be useful in future team transitions, and ongoing development.

## Acceptance Criteria
- [x] We have an understanding of what work is needed to update the platform so that it works with Angular 7.
- [x] we know what kind of impact an upgrade would have on the functionality of the site.
- [ ] A story is created for upgrading if we have the information we need and confirmed it will not have a burdensome impact on the site. 

## Tasks
- [x] research to find out what work is needed to accomplish an Angular 7 update.
- [x] angular2-csv update requires new functions written in report-results.component
- [x] ng-in-viewport v6.0.3 isn't properly attaching the inViewPortOptions, need to investigate
- [x] ngx-breadcrumbs hasn't been supported in over 2 years, need to find a replacement package
- [x] util.spec.ts http tests failing due to RXJS's new handling of objects and throwError, need to investigate.
- [x] go through https://update.angular.io/
- [ ] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Requires refactoring. 
Opportunity to improve the speed of load time.
Shouldn't move to production until we can verify it won't have impact on the functionality of the site.

**Comment by mtlaney** [comment]
Angular 7 and rxjs version 6 have been successfully installed in the application and most packages have been upgraded for the new release.

Below are a list of things left for me to do to complete full angular 7 functionality.
- [ ] angular2-csv update requires new functions written in report-results.component
- [ ] ng-in-viewport v6.0.3 isn't properly attaching the inViewPortOptions, need to investigate
- [ ] ngx-breadcrumbs hasn't been supported in over 2 years, need to find a replacement package
- [ ] util.spec.ts http tests failing due to RXJS's new handling of objects and throwError, need to investigate.

**Comment by ASprinkle** [comment]
@mtlaney I updated the story above and checked appropriate boxes.

**Comment by aaronburk** [comment]
I reviewed in staging.  Performance was adequate.  I will review again in production as a public user
