### ISSUE TITLE
As a temp outfitter, I want an application experience with minimal usability concerns

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#396]
## Notes
place holder card for additional cards from temp outfitter usability tests.

## Acceptance Criteria
- [ ]

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Was a place holder, closing due to redundancy with
