### ISSUE TITLE
As a repeat special use applicant, I would like to reuse some of my existing application data so that I can save time.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#398]
## Acceptance Criteria
- [ ] If I am an applicant who has applied before, I can auto-fill some of the data in a previous application to save me time.

## Tasks
- [ ] Define "some": what are the important fields that an applicant would want to have repopulated, OR define what changes from application to application when an application is a return user.
- [ ] PO approved.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle @davemcorwin same as #532: Have we solved the development question and the privacy question for design to pick this up?

**Comment by ASprinkle** [comment]
@lisaredux agreed - redundant with #532. 
532 captures both storing data and the saving the application to return later.
Therefore I am closing this story.
