### ISSUE TITLE
As a xmas tree user, I would like to have accurate instructions on how and when to cut my tree

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#401]
## Notes
xmas tree content updates

## Acceptance Criteria
- [x] forest requested changes made

## Tasks
- [x] gotten the requested changes made
- [x] Changes for the ARP
- [x] changes for Mt. hood
- [x] changes for Flathead
- [x] changes for shoshone

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
@ASprinkle I just found a list of what the different content files are: https://github.com/18F/fs-open-forest-platform/blob/dev/wiki/christmas-trees/content/markdown-files.md.

If you're creating a little cheat sheet for yourself on how to update that content, let me know, and I can add it to our documentation.

**Comment by lauraGgit** [comment]
@ASprinkle gotten feedback for all the forests

**Comment by ASprinkle** [comment]
@lauraGgit I completed the requested content changes for the ARP and hopefully linked everything to this issue ok.

**Comment by ASprinkle** [comment]
The Flathead NF wanted to see language that tells the forest visitor that the online Christmas tree permit is only valid on the Forest indicated on the permit.  R1 xmas tree permits issued at offices are valid across all NFs in the region and do not have expiration dates.  I updated the content common permit rules to add this language, as it applies to all participating pilot forests (permit expires, valid only for NF indicated on permit)

**Comment by lauraGgit** [comment]
I've reviewed an merged in all the content changes that @ASprinkle has made so far. They should be deployed to staging in <20 minutes.

**Comment by ASprinkle** [comment]
I reviewed the changes on the staging site - they look great!
