### ISSUE TITLE
Content edit titles match top level side bar menu

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#403]
## Notes
When making content changes, it is helpful to have the section titles in the content editing interface match (or more closely match) the top level sidebar menu on the website.

## Acceptance Criteria
- [x] Mt. Hood edit section titles match website menu headers
- [x] Shoshone edit section titles match website menu headers
- [x] Flathead edit section titles match website menu headers
- [x] Arapaho and Roosevelt edit section titles match website menu headers

## Tasks
- [ ] update tests.
- [x] identify the areas for the Mt. Hood that will need to be updated to match the website headers
- [x] identify the areas for the Shoshone that will need to be updated to match the website headers
- [x] identify the areas for the Flathead that will need to be updated to match the website headers
- [x] identify the areas for the Arapaho and Roosevelt that will need to be updated to match the website headers
- [ ] Change references in instruction components to reflect new file names.
- [ ] Consolidate markdown files based on top level sidebar navigation.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This is not MVP - the team has been able to make content updates with out much issue. However, making this change may make it more intuitive for future team member rotations or future content edit needs.
