### ISSUE TITLE
As product owner I'd like to know more about the traffic to the site

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#412]
## Notes
We currently have the Digital Analytics Program logging our events to google analtics, but we might want to talk with the USFS web managers about if we want to add more to get more granular data.

`<script async="" src="https://www.google-analytics.com/analytics.js"></script><script async="" id="_fed_an_ua_tag" type="text/javascript" src="https://dap.digitalgov.gov/Universal-Federated-Analytics-Min.js?agency=USDA&amp;subagency=FS"></script>`

## Acceptance Criteria
- [ ] confirm/ add google analytics to frontend

## Tasks
- [ ] remove duplicative `ga` script
- [ ] add in pageviews to the router - https://codeburst.io/using-google-analytics-with-angular-25c93bffaa18

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by tdlowden** [comment]
Hey all. I just took a look at the source code and tested DAP GA with Tag Assistant. The traffic appears to be coming in as expected:

![screen shot 2018-10-31 at 4 47 39 pm](https://user-images.githubusercontent.com/6556888/47817724-ce0c1d00-dd2c-11e8-8173-f5ade60ffc06.png)

 and the source code reflects the correct tag:
![screen shot 2018-10-31 at 4 47 39 pm](https://user-images.githubusercontent.com/6556888/47817739-db290c00-dd2c-11e8-90f4-5d3d0a892264.png)


I think you can close!
