### ISSUE TITLE
Users can access staging without logging in

### ISSUE THREAD

**Issue by suprenant** [18F/fs-open-forest-platform#418]
## Notes
This will be helpful for non-public users to test out changes before requesting or creating them live on the production site. Changes to staging site do not impact production site. Without a password, the staging site could be used by Open Forest administrators at the pilot forests for training/or testing. This would continue to be used by the development team.

tl;dr: Now that we have ATO, we don't need a password on staging, so we can remove it.

## Acceptance Criteria
- [x] The staging site does not ask for a password when loading.
- [ ] The staging site loads the admin functions (generate reports, change season dates, change cutting area dates, request content changes).

## Tasks
- [ ] update the circle config to remove the dev environment password.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by suprenant** [comment]
@lauraGgit as discussed

**Comment by lauraGgit** [comment]
Update from a discussion with @adborden: We technically no longer need a password on this, and the concern about PII entering SUDS DEV is mitigated by the restricted access to the admin side of things & we could add a warning just for stading. cc @ASprinkle

**Comment by lauraGgit** [comment]
@ASprinkle based on your acceptance criteria, no!

**Comment by ASprinkle** [comment]
This is the link I used to access staging. https://forest-service-trees-staging.app.cloud.gov/christmas-trees/forests I was not prompted for a password.  However, when I get there the admin tabs (generate reports, change dates etc.) are not available.
![image](https://user-images.githubusercontent.com/33435621/48573758-16e1db00-e8c2-11e8-9634-ee1194c68a69.png)

**Comment by ASprinkle** [comment]
Access to the admin functions on the staging site https://forest-service-trees-staging.app.cloud.gov/admin/christmas-trees/reports routes me through eAuth successfully (using Chrome).
