### ISSUE TITLE
Credit card billing confirmation displays "Open Forest permit" instead of "e-permits"

### ISSUE THREAD

**Issue by suprenant** [18F/fs-open-forest-platform#424]
What we're after:
 - "USFS e-permits 703-605-4803 DC" appears on the credit card statement for purchased Christmas tree permits. We want this to be changed to include "Open Forest permit" in place of "e-permits" so we have consistent language across the permitting experience. 

## Acceptance Criteria
- [ ] Credit card transactions display "USFS Open Forest permit 703-605-4803 DC"

## Implementation steps
- [ ] coordinate with Pay.gov to update text.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

![47871200-b2565480-ddc8-11e8-9fda-d3fcd4d2e7a8](https://user-images.githubusercontent.com/1452369/48009611-b0023c00-e0e1-11e8-88c6-53b9860ffa8c.jpg)

**Comment by annepetersen** [comment]
Though I think we still want "permit" to exist in the billing confirmation, so: "Open Forest permit."

**Comment by suprenant** [comment]
@annepetersen noted and edited – thanks. 

@ASprinkle here is this issue we discussed. Feel free to edit if there are any changes you'd like to make here.

**Comment by suprenant** [comment]
Archiving in lieu of: https://trello.com/c/BFqNiuKP/1045-credit-card-billing-confirmation-displays-open-forest-permit-instead-of-e-permits
