### ISSUE TITLE
Update ARP Map for Canyon Lakes Cutting Area

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#427]
## Notes
This is a second update to the Canyon Lakes Cutting Area map per changes that the ARP made.

## Acceptance Criteria
- [x] Map updated with Alt Text update.

## Tasks
- [x] Create thumbnail
- [x] Upload new image files
- [x] Add alt text

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Map for update provided by ARP 
[CLRDRedFeatherChristmasTree_ARP 1162018.pdf](https://github.com/18F/fs-open-forest-platform/files/2555275/CLRDRedFeatherChristmasTree_ARP.1162018.pdf)

**Comment by ASprinkle** [comment]
PO reviewed - looks great on staging
