### ISSUE TITLE
As a user I want to know the information on each Forest's page is accurate and up to date

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#428]
## Notes
Created this issue to capture the other misc. content edits outside of "how and when to cut a tree" as described in 401.

## Acceptance Criteria
- [x] A forest's requested edits have been made, and consistency is maintained where possible.

## Tasks
- [x] Mt. Hood and Shoshone: add "National Forest" after the forest's name in the contact us section. (requested from MTH, but also applicable to Shoshone).
- [x] Flathead: Confirm if the allowable quantity is 2 or 3. If change is needed, make edit throughout Flathead pages.
- [x] Mt. Hood and Shoshone: Clarify helpful cutting tips RE overcrowded vs. "dense forested area", and ensure "all people and vehicles" are out of the path of the tree. (requested from ARP, but applicable to all).
- [x] Shoshone NF address updates in Contact Us

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
Moving back into in progress because of deployment issues.

**Comment by ASprinkle** [comment]
Confirmed 3 tree limit on the Flathead NF - no changes needed there.

**Comment by ASprinkle** [comment]
@lauraGgit  The changes look great on staging!

**Comment by lauraGgit** [comment]
Merged to master in #441
