### ISSUE TITLE
As an admin, I need to see the number of spectators in a non-commercial application

### ISSUE THREAD

**Issue by annepetersen** [18F/fs-open-forest-platform#443]
## Notes
Spectator number not showing to the admin despite being present in what was filled out. Number shows on non-commercial user's email, but not on SUDS or even the Open Forest interface.

Screenshots:
User email listing number of spectators:
<img width="574" alt="user email with spectators" src="https://user-images.githubusercontent.com/5359122/48217545-45553880-e34d-11e8-9601-7e52deba505e.png">

Admin Open Forest view with no spectator number visible:
<img width="675" alt="admin of view no spectators" src="https://user-images.githubusercontent.com/5359122/48217733-c7456180-e34d-11e8-9cb3-4b5810c64b1f.png">

SUDS view with no spectator number visible:
<img width="704" alt="suds view no spectators" src="https://user-images.githubusercontent.com/5359122/48217888-3ae76e80-e34e-11e8-9dd9-1247081c9b7c.png">

permit created in Word with no spectator number visible in autofilled data:
<img width="708" alt="permit word document no spectators" src="https://user-images.githubusercontent.com/5359122/48217999-77b36580-e34e-11e8-959d-e85d7162e6ae.png">

## Acceptance Criteria
- [x] Spectator number that was entered is clear and evident to admins in all appropriate areas: admin Open Forest, SUDS, permit in Word

## Tasks
- [x] needs refinement
- [x] PO approved.

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] Server actions captured by logs
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by carlsonem** [comment]
Amber needs to know how to access SUDs.

**Comment by davemcorwin** [comment]
Blocked by lack of ability to confirm in staging due to issues connecting to SUDS

**Comment by davemcorwin** [comment]
@ASprinkle I think the issue is that Smokey Bear (the name on the application we typically use) exists in SUDS but doesn't have an address. Our application assumes that if the contact exists then it also has an address.

1) Can you manually add the address for Smokey Bear in SUDS?
2) Can you test this in staging with an application for a new person?

**Comment by ASprinkle** [comment]
I do not know if I canadd Smokey Bear's address into SUDS so I went into the SU Staging site and tried to go through the process again using "New Name"... I was unable to submit my application, I received an error, but it was unclear what the error was for. See screen shots:

![image](https://user-images.githubusercontent.com/33435621/56779003-de59fd80-678d-11e9-9ba1-b9c1fd8ba23c.png)

![image](https://user-images.githubusercontent.com/33435621/56779018-f3cf2780-678d-11e9-8934-97305a750e9a.png)

![image](https://user-images.githubusercontent.com/33435621/56779028-0184ad00-678e-11e9-9ce3-caf35a0f9e09.png)

![image](https://user-images.githubusercontent.com/33435621/56779036-0a757e80-678e-11e9-8a75-c019c388e635.png)

![image](https://user-images.githubusercontent.com/33435621/56779042-12352300-678e-11e9-97fb-6d74d9fabff0.png)

**Comment by davemcorwin** [comment]
I believe you should be able to update the address for that contact in
suds. Re the error, we have a open issue for this, use start and end time
that are in the am and it should work.

**Comment by aaronburk** [comment]
This is related to 601 per standup 4/30/19

**Comment by ASprinkle** [comment]
ID on Open Forest platform: 100. 
 Activity Description: Testing the activity. 
 Location Description: Testing the Place. 
 Start Date Time: 2019-06-01T10:00:00Z. 
 End Date Time: 2019-06-04T11:00:00Z. 
 Number Participants: 89. 
 Number Spectators: 42.

**Comment by ASprinkle** [comment]
Confirmed that a non-commercial group use application that is approved in Open Forest transfers to SUDS without error, and includes the number of spectators.

**Comment by ASprinkle** [comment]
Confirmed that the information from Open Forest transfers to SUDS printed permit authorization also
![image](https://user-images.githubusercontent.com/33435621/57092432-48a7fc00-6cc0-11e9-917d-2160a50874f4.png)
