### ISSUE TITLE
As an ARP admin I want to see the cutting area dates updated to reflect the actual dates

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#458]
## Notes
 During the Open Forest demonstration for the ARP (11/14) individuals request an update to the Cutting Area dates for Elk Creek and for Red Feather Lakes. Update to the Season date was also request.
Additionally in the Rules and Guidelines they noted that the times reflected for each cutting area should be the same as what's shown in the When to Cut Your Tree section of the site.

## Acceptance Criteria
- [x] Elk Creek Cutting Area dates show Dec 1 - 8
- [x] Red Feather Lakes cutting area dates show Dec 1 - 9
- [x] Season Date shows through Jan 6.
- [x]  Rules and guidelines updates completed, if confirmed needed.

## Tasks
- [x] Make the cutting area date updates
- [x] Confirm whether not the Rules and Guidelines for both cutting areas should be updated to read " The entrance opens at 8:30 a.m. You must leave the cutting area by 2:30 p.m."
- [x] Make the rules and guidelines update if confirmed necessary.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
I updated the ARP dates using the Open Forest Production site for Administrators.  I am still waiting on the confirmation for whether or not an update is needed to the Rules and Guidelines page.

**Comment by ASprinkle** [comment]
Confirmed updates with ARP for the R&G page. Looks great on staging!
