### ISSUE TITLE
Spotted Bear Ranger district location may be an error?

### ISSUE THREAD

**Issue by aaronburk** [18F/fs-open-forest-platform#464]
## Notes
The spotted bear ranger ditrict meesage on the Flathead says it changes locations seasonally, yet the address for both locations is the same and only the Phone # is different

## Acceptance Criteria
- Correct location information (if needed)

## Tasks
Ensure location information and update content
## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
![image](https://user-images.githubusercontent.com/25828899/48673076-bcd45600-eb0b-11e8-92ac-c33f65ccfc4c.png)

**Comment by ASprinkle** [comment]
I verified the information with the Spotted Bear administrative support assistant Lincoln Seals and he informed that "Yes this is correct.  We use the Hungry Horse office for mail and shipping year round.  The summer office site has no real address per say."
