### ISSUE TITLE
As a Forest Service administrator I want to know that the Report Generated dates and query dates match so that I know the data is accurate.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#468]
## Notes
The query dates and the report data/report generated dates should match.

Currently on Production, the start and end date for the query and the report generated dates do not match. The report generated date is one day earlier (for start and end) in the title.
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/013e132f-5365-4902-b586-587af78d096f)

This bug also creates an issue when an Open Forest Administrator wants to query a 24-hour period (1 day) of permits sold.  When 11/19/2018 is selected for a start and for an end date, the report that is generated produces information for 11/18/2019 showing that zero permits are sold. If the Administrator is not carefully reading the title of the report, they will believe the information presented as accurate for their query, when it really is not.
![image](https://user-images.githubusercontent.com/33435621/48792014-08236b80-eca8-11e8-8c0f-7280700f0b6f.png)

## Acceptance Criteria
- [x]  The query dates and the report generated dates match.
- [x]  The data shown in the report is within the bounds of the dates queried for the forest selected.
- [x] Time zones for generating reports apply to the Forest a report is being generated for.

## Tasks
- [x] Determine timezone handling from the server or the frontend is creating the discrepancy between input and output.
- [x] PO Approved

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] Server actions captured by logs
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
This was an issue this morning when an OF admin on the Mt. Hood tried to query a report for one day (11/19)
![image](https://user-images.githubusercontent.com/33435621/48729218-f2507080-ebeb-11e8-86f7-d94a66873a15.png)

**Comment by thimonas** [comment]
In report.component.ts, may replace this.forest.timezone in 3 places with an empty string, as shown below:
 
      // original   moment.tz(this.form.get('dateTimeRange.startDateTime').value, this.forest.timezone).format('YYYY-MM-DD'),
      // original  moment.tz(this.form.get('dateTimeRange.endDateTime').value, this.forest.timezone).format('YYYY-MM-DD')
      moment.tz(this.form.get('dateTimeRange.startDateTime').value, "").format('YYYY-MM-DD'),
      moment.tz(this.form.get('dateTimeRange.endDateTime').value, "").format('YYYY-MM-DD')


      // original  return moment.tz(this.form.get(dateField).value, this.forest.timezone).format('MM/DD/YYYY');
      return moment.tz(this.form.get(dateField).value, "").format('MM/DD/YYYY');

**Comment by lauraGgit** [comment]
Hi @thimonas are you able to fork the repository, until we can you access and then make a pull request with this change?

**Comment by ASprinkle** [comment]
[PermitNumberReconcilitationNov20.docx](https://github.com/18F/fs-open-forest-platform/files/2631348/PermitNumberReconcilitationNov20.docx)

I am attaching a document with some print screen shots of how date inaccuracies can make it appear as if a single permit number was issued twice...

**Comment by thimonas** [comment]
[468_Query_Range_Flow_Details For_Discussion.docx](https://github.com/18F/fs-open-forest-platform/files/2639765/468_Query_Range_Flow_Details.For_Discussion.docx)

**Comment by ASprinkle** [comment]
@thimonas @lauraGgit do we have time today to meet regarding this issue?

**Comment by thimonas** [comment]
Hi Laura. Is 3 pm this afternoon a good time to review 468 query range flow details? :)

**Comment by lauraGgit** [comment]
Looks like the admin query report is being set to forest timezone - but then not being converted back to UTC when its sent to the server. https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/app/trees/admin/report/report.component.ts#L153

The resulting output is also still in UTC: and needs to be put relative to the forest timezone: https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/app/trees/admin/report/results/report-results.component.ts#L44

The start and enddate here need to also be converted back from UTC to the forest timezone:https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/app/trees/admin/report/results/report-results.component.html#L2

**Comment by lauraGgit** [comment]
More on how the timezones were originally implemented: https://github.com/nciinc/fs-permit-platform/issues/346

https://github.com/nciinc/fs-permit-platform/pull/374

**Comment by thimonas** [comment]
The permit.christmasTreesForest.timezone added on the record retrieval of a reported range at https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/controllers/christmas-tree-admin.es6#L30 vs https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/controllers/christmas-tree-admin.es6#L36 when retrieving an individual record, explain the reported date differences between the individual record retrieval and the multiple reported records.

**Comment by thimonas** [comment]
In 468-report-dates, completed the fix for the date range, querying properly at forest time and retrieving 
correctly issue and expire dates.
1. Observed that a permit is saved in the database as default, database UTC time.

2. Observed that there is not  time transformations taking place during a permit save, in angular or node server.

3. No need to transform time when asking the time-range question in angular. Just passing the date range to node.
    
4. On asking the question of time-range in UTC terms in node:
Conversion to UTC from forest time for the next date takes place at https://github.com/18F/fs-open-forest-platform/blob/468-report-dates/server/src/controllers/christmas-tree-admin.es6#L86
Conversion to UTC from forest time for the start date takes place here https://github.com/18F/fs-open-forest-platform/blob/468-report-dates/server/src/controllers/christmas-tree-admin.es6#L87

5. Changed the statement to convert the issueDate time for the retrieved record from database UTC to forest time. https://github.com/18F/fs-open-forest-platform/blob/468-report-dates/server/src/controllers/christmas-tree-admin.es6#L30

6. Changed the statement to convert the expiredate time for the retrieved record from database UTC to forest time. 
https://github.com/18F/fs-open-forest-platform/blob/468-report-dates/server/src/controllers/christmas-tree-admin.es6#L32

**Comment by lauraGgit** [comment]
@thimonas are you planning on working of of @adborden's  PR?

**Comment by ASprinkle** [comment]
@thimonas update from stand up: working with UTC time for permits; updated original PR

**Comment by ASprinkle** [comment]
In reviewing the acceptance criteria for this story, I think we should edit "data shown" so that it captures the "issue dates".  Data shown didn't seem specific enough. So if a date range is queried (including a 24-hour period) all of the permits that have an "issue date" within that query range would be populated into the report for the selected forest.  

I would also like to add an AC that says "Issue dates for individual permits are consistently represented in both the individual permit report and the date query report" -referencing the doc from above https://github.com/18F/fs-open-forest-platform/files/2631348/PermitNumberReconcilitationNov20.docx

**Comment by ASprinkle** [comment]
From stand up:  Tom is working on unit testing this week to get it ready for PO viewable in staging.

**Comment by ASprinkle** [comment]
Mike is reviewing information from Tom.

**Comment by ASprinkle** [comment]
I went into staging and ran a report for Nov. 20 through Nov 21 2018 for the ARP.  This is what was returned:
![image](https://user-images.githubusercontent.com/33435621/53262874-a4d11d00-368c-11e9-9a40-3e759dca293e.png)

In my record of permit sales, I show that Nov 20 Through Nov 21 there were 53 permits issued/sold on Nov. 20, and 61 permits on Nov 21.

When I query the dates Nov 20 through Nov 21 I would expect to see a list of permits that were issued on those days...  thoughts?

**Comment by aaronburk** [comment]
Reviewed and approve
