### ISSUE TITLE
[SPIKE] As Christmas tree applicant if I have a credit card declined, I want to be notified that it was declined, know what I need to do next.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#475]
## Notes
Some cards are being declined at pay.gov and we are not clear whether or not people are being notified of the decline. We are also not clear where they are directed to once their card is declined.

## Acceptance Criteria
- [x] We know what kind of message the forest visitor receives when their card is declined.
- [x] We know where the forest visitor is directed once their card is declined.

## Tasks
- [x] Clarifying the process and creating a new issue if a fix is needed.
- [x] Verify that an incomplete permit (i.e., declined credit card) isn't showing up on the report of permits issued (generate a report).

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
The Try/catch statements in the the [pay.gov](https://github.com/18F/fs-open-forest-platform/blob/2134ceda4c69afdd77482b36afc7ce5a8c6c667c/server/src/services/paygov.es6#L211) & [christmas tree controllers](https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/controllers/christmas-tree.es6#L250) mean that the pay.gov errors  are never properly handled- resulting in the "spinning wheel of death" and the long average resolution times we are seeing in new relic...

Creating a new card here:

**Comment by ASprinkle** [comment]
we now know they get the spinning wheel of death and no message. (ac above)
we now know know that they continue  to sit at pay.gov (ac above)
I see you've created a new issue.
Have we been able to tell whether or not declined payments are showing up as permits in reports?

**Comment by lauraGgit** [comment]
@ASprinkle oh, yes, i'll go ahead, and take a look at the reports question!

**Comment by lauraGgit** [comment]
@ASprinkle ok, after some serious sleuthing (especially glad to have those test purchases from Aaron). Permits that receive these errors don't appear in the reports because they retain the permit status of `Initiated` and the reports only include permits with the status  of `Completed`
