### ISSUE TITLE
[Dec 20] Prepare Open Forest for potential government shutdown Dec. 21

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#476]
## Notes
Potential exists for a government shut down Dec. 7 when funding is due to run out.  As part of the shutdown process, we should prepare the site.

## Acceptance Criteria
- [x] Forest visitors are not able to purchase a Christmas tree permit during the shutdown.
- [x] The "buy permit" button is not available, nor is it accessible.
- [x] There is information on the main page that explains why permits are not available, subsequent forest pages are not accessible.

## Tasks
- [x] Update the routes so that the main site doesn't redirect to Christmas trees, and so that it points to a shutdown page.
- [x] Obtain the shutdown language to add to the site.
- [x] Create new shutdown page.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Amber will add previous government shutdown information.

**Comment by ASprinkle** [comment]
Mike is waiting to submit a pull request pending a shutdown.

**Comment by ASprinkle** [comment]
Last to do: implement on Circle Ci.
Show user experience screen shot from staging
Test in staging
Midnight EST is shutdown deadline - implementation time
Amber and David to pair at 9pm PST to test/check
