### ISSUE TITLE
As a christmas tree applicant who is having issues with the system (or enjoying the system), I want to know that the email address on the Open Forest page is for help or feedback.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#477]
## Notes
The Open Forest Christmas tree page has the email address and the "General Information" phone number on the same line.  An applicant would not know by looking at it that the email address can be used for technical help or feedback.

## Acceptance Criteria
- [ ] There is a title next to the email address that clearly describes what the email address can or should be used for.
- [ ] The title is easy to read and understand between the email and the phone number.

## Tasks
- [ ] create copy for the title
- [ ] update the footer
- [ ] update the phone number display (on a new line)
## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lauraGgit** [comment]
@annepetersen @ASprinkle what was the text that you were looking for on this?

**Comment by annepetersen** [comment]
Either "Feedback/help:" or "For help or feedback:"

@ASprinkle, what do you think?

**Comment by ASprinkle** [comment]
@annepetersen @lauraGgit "For help or feedback"

**Comment by lauraGgit** [comment]
This look ok @annepetersen / @ASprinkle 
![image](https://user-images.githubusercontent.com/5840989/49242470-d95c7200-f3d8-11e8-942e-c112a208dba6.png)

**Comment by ASprinkle** [comment]
Yes!

**Comment by ASprinkle** [comment]
I am not able to see this on the staging site..

**Comment by ASprinkle** [comment]
Looks great!
