### ISSUE TITLE
As a Christmas tree applicant I don't want to accidentally view the staging site when seeking an Open Forest Christmas tree permit and information.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#479]
## Notes
A google search for "Open Forest Christmas trees" returned a number of hits including the staging site.  A user could potentially go through the entire purchase process on the staging site, obtain a permit, and not have their card charged (as was the experience for Amber when testing the purchase process prior to launch)

## Acceptance Criteria
- [x] access to the staging site is restricted (i.e., password protected, or otherwise).

## Tasks
- [x] Add a protection to the staging site.
- [x] Share the protection with the Open Forest administrators so that they can continue to access staging if they need/want to.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
