### ISSUE TITLE
As Christmas tree applicant if I have a credit card declined or other pay.gov, I want to be notified that it was declined, know what I need to do next.

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#483]
## Notes
- see the notes here on the spike card: https://github.com/18F/fs-open-forest-platform/issues/475#issuecomment-442203428

This can be tested in staging by using CC number 4005550000000001 when purchasing a permit.

## Acceptance Criteria
- [x] As a christmas tree purchaser, i would like to know that i had a pay.gov error.
- [ ] ~if my cc was declined, I would like the option to go back to pay.gov and submit a new payment 
method~
- [x] as a system admin I can adequately triage errors.

## Tasks
- [x] remove the try catches in the pay.gov/christmas tree controllers
- [x] ensure that xmas tree purchasers are directed to the correct place.
- [ ] ~move away from express winston to better view the nested json in kibana~
- [x] verify (once in production) that timeouts are reducing 
- [x] verify that errors are being captured in a way that we would expect given our logging updates.
- [x] PO approved.

## Definition of Done
- [x] Code unit / e2e tested and comply with QWASP
- [x] Server actions captured by logs
- [x] No new security vulnerabilities
- [x] Internal team code review
- [x] Documentation / readme.md / CircleCI updated
- [x] Docker updated
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by ASprinkle** [comment]
From stand up - Laura will post an image of the alert on pay.gov confirmation page for follow up. Refactoring needs identified, Laura is working on that.

**Comment by lauraGgit** [comment]
Here is the alert error when the CC is declined - and @annepetersen / @lisaredux 
https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/app/application-forms/tree-application-form/tree-permit-view/tree-permit-view.component.html#L93

![image](https://user-images.githubusercontent.com/5840989/49598771-59d92080-f94d-11e8-8f67-cbf5dfa7557e.png)

**Comment by lauraGgit** [comment]
It was a container div issue! Now looks like this:
![image](https://user-images.githubusercontent.com/5840989/49599473-1f708300-f94f-11e8-926c-c3f5339efe2f.png)

**Comment by lauraGgit** [comment]
So the next question - is that the link below currently is supposed to repopulate the fields they had entered, but it does not, which is in part ok, because we would have to update how a permit that had previous transaction errors get overwritten.

But @ASprinkle do we want to go through the effort of repopulating it, or is it ok, that is it empty?

**Comment by ASprinkle** [comment]
@lauraGgit I think it is ok that it is empty for now.  in the future, preference would be for fields to repopulate so that the user experience is less frustrating - but for purposes of MVP for the time being, I think it is appropriate to satisfy the messaging around CC declines.  Also, not repopulating fields means the user would have an opportunity to re-check the information they entered; in the event it was an operator entry error.

**Comment by ASprinkle** [comment]
Some technical improvements before we close this story: Org of server code (already in there), implementing stricter style rules for the server (in progress), improve the logging (not started yet).

**Comment by ASprinkle** [comment]
I was able to get a permit on staging site successfully.

**Comment by ASprinkle** [comment]
pushed to production- credit card errors. No errors and transaction times are down since (possibly less activity).

**Comment by ASprinkle** [comment]
Initial fix may not have worked; investigating further.

**Comment by ASprinkle** [comment]
from stand up: almost done with refactoring updates.

**Comment by suprenant** [comment]
Moving this to blocked/waiting pending code review (either Mike L. once he has access or someone to scrub in from 18F).

**Comment by ASprinkle** [comment]
@davemcorwin is there a way to test the error message on the staging site? Perhaps you can drop in a screen shot. I hesitate to "change season dates" for a forest in production in order to test a credit card error transaction.

**Comment by davemcorwin** [comment]
@ASprinkle I extended the season for the Arapahoe forest in staging so you can buy permits there. I'm trying to find a payment information that will trigger an error so we can test. I just tried with an accurate CC, but all other info incorrect and it succeeded...

**Comment by davemcorwin** [comment]
@ASprinkle I don't think this fix is working properly. I believe I am generating errors from Pay Gov in staging, but the UI is not displaying this. I will move this back to in progress and investigate and will update with details on how to trigger errors in Staging in the documentation.

**Comment by ASprinkle** [comment]
from stand up: working on finding out how we can test/see this on staging.

**Comment by ASprinkle** [comment]
@davemcorwin needs documentation for using/testing with Pay.gov - waiting to find out information on this.

**Comment by ASprinkle** [comment]
From stand up: able to do some debugging in staging environment. Working on local environment mimic expectations from pay.gov to perform accurate tests.

**Comment by ASprinkle** [comment]
Mike and Dave pairing on this to confirm changes before approving and merging.

**Comment by ASprinkle** [comment]
Is there a way to see what the notification looks like?

**Comment by aaronburk** [comment]
Reviewed and approved
