### ISSUE TITLE
[Spike] As the Open Forest product owner I want to be able to measure qualitative success of the pilot.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#496]
## Notes
Measure success (user satisfaction/customer experience) at the end of the season.  For example, at the end of the season can we email known customers and ask them our customer satisfaction questions? 

2 or 3 sessions

## Acceptance Criteria
- [x] We have an idea of what we're able to do to gather user satisfaction from users who have completed the life cycle of the process Open Forest information -> Permit Purchase online -> Gathering -> Disposal.
- [x] We have an idea about how to display satisfaction (qualitative success). 
- [x] We know if we can use/retrieve email addresses from Christmas tree applicants.
- [x] We know if we can contact applicants for future use/satisfaction review (review PIA).

## Tasks
- [x] set brainstorming/collaboration sessions around this topic

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Regarding the question of access to email addresses from @lauraGgit "we can extract them, but there is a question about whether we can reach out to them, given we didn't say that we might use they're email to do that in advance. "  @tram was going to review the PIA for this aspect.

**Comment by ASprinkle** [comment]
Notes on discussion:
-know who the audience is that we would report qualitative user satisfaction to: stakeholders (all levels)
-report user/customer satisfaction by grouping themes from feedback into findings and recommendations
-help requests data

**Comment by ASprinkle** [comment]
The Privacy Impact Assessment https://openforest.fs.usda.gov/assets/files/OpenForestePermits-Privacy-Impact-Assessment-2018.pdf has been reviewed. The following statements are from the PIA. Based on the following statements, it appears we should not retrieve email addresses (PII) because we did not go through the SORN process for Open Forest to store and retrieve PII information.

"[The System] will be used to facilitate discussions about the permitting process. It will be also used to generate statistics of usage of special uses and forest products on the Forest."

"...PII is used only for its original purpose of issuing a permit... PII is not able to be queried
through the ePermits system and thus is not retrieved by personal identifier"

Section 6.1 "Does this system require a SORN and if so, please provide SORN name
and URL.  - No. Information is not able to be retrieved or queried via PII."
