### ISSUE TITLE
[Spike] As a Christmas tree permit holder I want to know how to responsibly dispose of the Christmas tree I gathered from the National Forest.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#497]
## Notes
Research spike to find out if we need to add information to the Open Forest page about responsible disposal of a National Forest Christmas tree.

Time Box 2-3 days

## Acceptance Criteria
- [x] We know whether or not this is an important issue.
- [x] We create a story to update Open Forest content if it is an important issue to pilot forests.

## Tasks
- [x] Amber finds out from pilot forests if this is something that is commonly inquired about and if information on it should be added to the Open Forest site.

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Questions sent to pilot forests:
Does your forest share information with Christmas tree cutters on how they should responsibly dispose of their tree after the holidays?  
Flathead: No

Does your forest receive this question often from Christmas tree cutters?
Flathead: Mostly no.

**Comment by ASprinkle** [comment]
Heard back from someone else on the Flathead:  "We do not get a lot of these but I tell people that they need to follow any city or county regulation as far as trash pick up and land fill drop off. I looked and I don't have any "official" information for discarding a Christmas Tree but a standard answer would be helpful"
Waiting on response from SHO and ARP

**Comment by ASprinkle** [comment]
response from ARP: "CLRD used to provide the information on what to do with there the tree but don't currently but could if needed. "

**Comment by ASprinkle** [comment]
Result: this is not an important issue for pilot forests at this time, therefore we do not need to create a story to respond to this potential need.
