### ISSUE TITLE
As an onboarding developer, I want to make sure I have accurate instructions to get started with our workflow

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#503]
## Notes
As a developer, I want the documentation to reflect our current mode of operations, which is using `npm` instead of `yarn` for node package management.

## Acceptance Criteria
- [x] References to `yarn` are replaced with `npm`

## Tasks
- [x] Find and replace references to `yarn` with equivalent `npm` command

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
To avoid potential downtime issues, complete this card after Christmas day.
