### ISSUE TITLE
As an onboarding developer, I want to make sure I have helpful instructions for running e2e tests with Protractor

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#504]
## Notes
Add documentation around handling issues that may occur when using `Protractor/chromedriver` for ent-to-end testing of the application frontend.

A developer may get an error about `chromedriver` requiring a different version of `chrome` than what is installed.

## Acceptance Criteria
- [x] Additional documentation in the Readme is clear and helpful!

## Tasks
- [x] Add documentation to the Readme

## Definition of Done
- [ ] Code unit / e2e tested and comply with QWASP
- [ ] Server actions captured by logs
- [ ] No new security vulnerabilities
- [ ] Internal team code review
- [ ] Documentation / readme.md / CircleCI updated
- [ ] Docker updated
- [ ] Compare finished design with mockup
- [ ] Usability tested
