### ISSUE TITLE
As a user I want to see the most recent updates to the site without having to clear my cache so that I know I am receiving up to date information.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#522]
## Notes
This story was created when we updated the website in preparation for the government shutdown. We had to clear our cache in order to see the updated government shutdown page.

Originally developer oriented: I need to remember to fingerprint the built JS so caches are busted on deploy as a follow up from preparing the site for the government shutdown.

## Acceptance Criteria
- [x] file name is changed to unique version so that page loads with updated information without user having to clear their cache.

## Tasks
- [x] Research tasks and update this task list to find out how much time this update would take.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
On Staging I can see that the javascript filenames include a hash of the contents and they are fetched successfully from the server. We should confirm on the next code change that the hash also changes.

![screen shot 2019-02-13 at 9 29 18 pm](https://user-images.githubusercontent.com/6662371/52764846-82793880-2fd6-11e9-90ee-b7a108b7704e.png)

**Comment by ASprinkle** [comment]
That is great! Would it be a good idea to put a task card in new issues to capture your suggestion of "We should confirm on the next code change that the hash also changes" so that we don't forget?

**Comment by davemcorwin** [comment]
The filename for our JS (main.*.js) has changed on staging so this looks good!
![screen shot 2019-02-19 at 9 14 26 am](https://user-images.githubusercontent.com/6662371/53033864-e3fe3480-3426-11e9-888d-2ff9060578da.png)
