### ISSUE TITLE
[Spike] As a security operator in FS, I would like to know what vulnerabilities are disclosed in the system (migrate existing snyk)

### ISSUE THREAD

**Issue by lauraGgit** [18F/fs-open-forest-platform#527]
## Notes
Migrate to FS owned Snyk org
- currently on Laura's snyk organization, should probably be on an FS one

## Acceptance Criteria
- [ ]  we understand what is needed to be able to shift to an FS one.
- [ ] LauraGgit is no longer the snyk org for any FS repo.

## Tasks
- [ ] research requirements on the FS side to be able to do this.
- [ ] create new snyk or identify existing snyk org, or replacement static scanner.
- [ ] update ci credentials for snyk in Circle.
- [ ] PO approved.

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Connected to Trello story [insert link].

**Comment by davemcorwin** [comment]
Blocked pending FS Snyk account

**Comment by carlsonem** [comment]
This is a duplicate issue of other issues created.
