### ISSUE TITLE
As a special use applicant, I want to know that the permit I'm applying for is only applicable on the MBS, so that I know I am applying at the right place.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#533]
## Notes

-The site currently reads: "Apply for a permit with Open Forest Mt. Baker-Snoqualmie National Forest"
-MBS should be priority information and Open Forest secondary. 
-For example, the Christmas tree platform requires a forest selection gate prior to continuing.
https://open-forest-staging.app.cloud.gov/mbs

## Acceptance Criteria
- [ ] An applicant knows they are at the right place to get a SU permit for the MBS.
- [ ] An applicant knows where they need to go to get a permit for a different forest.
- [ ] Plain language/common language (synthesis noted that "non-commercial" was confusing).
- [ ] Users can quickly understand which permit is right for them.

## Tasks
- [ ] Create content, content strategy for landing page
- [x] Design mock ups clearly labeled for the MBS
- [x] Evaluate mock ups
- [ ] PO approved.

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
Proposed design content update:
<h1>Mt. Baker-Snoqualmie National Forest </h1>
<h2>Apply for a permit</h2>

<img width="729" alt="screen shot 2019-02-25 at 11 21 43 am" src="https://user-images.githubusercontent.com/26801590/53352019-1066f480-38f0-11e9-84b4-67b5a10bd066.png">

**Comment by ASprinkle** [comment]
@lisaredux is there a way to work in "Open Forest" onto the landing page?  We've got the name of it on the Christmas tree site, and it would be good to have it somewhere here too.  perhaps "Apply for a permit through Open Forest"... or would that be confusing given the login.gov hint text below the header? Perhaps the hint text should read something like "...create a profile in login.gov to begin the process"

**Comment by lisaredux** [comment]
> @lisaredux is there a way to work in "Open Forest" onto the landing page? We've got the name of it on the Christmas tree site, and it would be good to have it somewhere here too. perhaps "Apply for a permit through Open Forest"... or would that be confusing given the login.gov hint text below the header? Perhaps the hint text should read something like "...create a profile in login.gov to begin the process"

@ASprinkle I see. The only issue I want to avoid is what Trammel mentioned as referring things as they are named internally by the Forest Service. Lemme make a few more mockups and see what you think.

**Comment by lisaredux** [comment]
@ASprinkle here are other versions of adding Open Forest and changing the type. 

Also, it seems that both Christmas trees and MPB don't give context to what Open Forest is. It might make sense to put something about Open Forest to answer: "what is Open Forest?" like an FAQs or just an info bubble if that fits into the schema. Otherwise, Open Forest might not mean much to applicants and the branding might fall a little short...my two cents. 

 <img width="789" alt="screen shot 2019-02-26 at 11 21 04 am" src="https://user-images.githubusercontent.com/26801590/53428360-a8301580-39b8-11e9-8dd5-6a09d3414513.png">
<img width="748" alt="screen shot 2019-02-26 at 11 16 50 am" src="https://user-images.githubusercontent.com/26801590/53428538-f80edc80-39b8-11e9-9f3d-f1d1490c725b.png">

**Comment by ASprinkle** [comment]
@lisaredux Thanks. The option above where MBS is large and green, and the "apply for a permit with open forest is smaller" it still helps the visitor understand that they are on the MBS would be preferred.  I agree that the "with open forest" piece is out of context. It seems kind of out of place.  Perhaps there is a better place for it somewhere else as part of the landing page redesign.

**Comment by DawnDesigner** [comment]
With Lisa's suggestions and pulling from this story and user requests, I've created a modification mockup that is more consistent with the Christmas Tree Permitting site - to help establish that look and feel that is very appealing to users - and also address some other problems the current layout creates. This new mockup address:

1. Consistent look and feel with the Christmas Tree landing page
2. Text of permit description not sitting over an image allowing the image to be brighter and unobstructed, and making the text easier to read
3. Clearly gives three options - Non-Commercial, Temp Outfitters and I just don't know help me
4. Users don't need to leave page to get clarity or get questions answered.
5. Gives a way to populate the title of the forest at the top of every page with the option to move from one forest to the other in future application releases (new issue to be created)
6. In full screen view gives full use of the screen real-estate while allowing for full responsive stacking in a tablet/mobile screen

![mtbakerlanding](https://user-images.githubusercontent.com/47989077/53813725-4ded0280-3f2c-11e9-9154-32f28a05c865.png)

**Comment by ASprinkle** [comment]
@DawnDesigner this is a great route to go.  I have some suggestions:
-can we condense the "Mt. Baker Snoqualmie National Forest" drop down and the "Apply for a Special Use Permit with Open Forest" sections, instead of breaking them through the page?
-Instead replace the "Special Use permits welcome, with the other language below it: "Welcome to the USDA National Forest Service digital..." 
-Instead of "USDA National Forest Service" It should be USDA Forest Service, no "national" in there.
-Condense the actionable button items - preference to the "Apply" buttons design examples vs the two buttons in the welcome box.  Perhaps under the welcome message in the welcome box we could have the National Forest listed there (similar to Christmas Trees site).
-Remove all Every Kid in a Park information. That is specific to Christmas trees only.

**Comment by DawnDesigner** [comment]
@ASprinkle , thanks for the comments.  I have now broken up this story into three stories since it covered more than just the title, but also branding etc .Thinking it will make it easier for development, and consideration and comments from the team (like congress trying to push a bill through with to many items).  

 I'll take the time to move your comments to relevant stories, or you are welcomed to visit them and preview.

#567 Make sure every page on application has title "Mt Baker-Snoqualimie " (this now has elevated to the fact the "Open Forest Permitting" should appear on every page to indicated to users all permitting is coming from the Open Forest umbrella. More to come)

#564 - Add hero top of page and use as look and feel for future permits so a large beautiful image for that forest can be featured (please read comments on story - each landing page will look different because the image is different and specific to that forest)

#565 Content boxes on landing page - to remove text over image and help clarify and answer questions without a lot of click and moving to other pages.

**Comment by ASprinkle** [comment]
If you're creating new stories, please create them in the user story format: "As a Blank, I want to Blank, so that I can Blank..."

567: Not sure if we want "Open Forest Permitting" on each page, or something different, perhaps just "Open Forest" somewhere discreetly. 

564: For MVP to get special uses up and running, I don't think we need to spend time on putting a picture from the forest at the top of every page.  Perhaps that could be a future/long-term goal, but I wouldn't recommend spending time on that while we ramp up Special Uses side for pilot launch.

565: Content boxes, roll over text:  this is interesting concept.  can we do that w/508 compliance, and as a mobile app?

**Comment by DawnDesigner** [comment]
Sorry Amber, I did use the standard user story format with the criteria as sited on other stories here, I  just didn't use that as the title of the issue. If you open the issue you can see the opening statement is user story formatted

I can change that. I was thinking that the user stories can get so long you often can't see enough of the story to see what the issue is about in the issues list - so I title the issues so it's clear.  Sorry for the confusion.

**Comment by lisaredux** [comment]
@ASprinkle @MelissaBraxton @DawnDesigner perhaps redundant with #567 - that right?

**Comment by ASprinkle** [comment]
Closing - Redundant with #567. It addresses the intent of this story in a broader way.  This story is specific to the MBS, but #567 has a broader context - thereby addressing the goal of this story.
