### ISSUE TITLE
As a special use applicant I want to know which permit to apply for so that I know I can choose the right application.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#535]
## Notes
Themes from the SU usability synthesis informed that the landing page could be refined with plain language, and less text.

## Acceptance Criteria
- [ ] Plain language/common language (synthesis noted that "non-commercial" was confusing).
- [ ] Users can quickly understand which permit is right for them.

## Tasks
- [ ] Needs refinement
- [ ] PO approved.

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
#533 addresses this issue. closing and updating 533 AC
