### ISSUE TITLE
As a FS admin I do not want a technically savvy person to be able to manipulate the cost of a permit when going through the Christmas tree purchase process, so that risk is reduced.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#539]
## Notes
When allowing the user to create a permit the following pieces of data are accepted from the user, however, they should be determined by the forest data as maintained by site admins:
- `orgStructureCode`
- `treeCost`
- `totalCost`

The result of this is that a technically savvy user could purchase a permit but specify any price they want, theoretically even a negative one, possible resulting in a credit (unless prevented by Pay.gov).

I also recommend updating the database to restrict the cost and quantity of permits on the Forest and Permit tables to be greater than or equal to 0.

## Acceptance Criteria
- [x] No change in UX
- [x] A savvy user CANNOT control the price of a permi

## Tasks
- [x] Add a constraint on the following database fields to require positive values
  - `forests.treeCost`
  - `forest.maxNumTrees`
  - `trees.treeCost`
  - `trees.totalCost`
  - `trees.quantity`
- [x] Remove the following fields from the payload expected by `christmasTreePermits.create` and populate them from the specific forest
  - `orgStructureCode`
  - `treeCost`
  - `totalCost`
- [x] Create tests to ensure that the above constraints are present.
- [x] PO approved.

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [x] Compare finished design with mockup
- [x] Usability tested
