### ISSUE TITLE
As a forest visitor who completed the permit purchase process I want the link to the permit in the email to take me to my permit, so that I can print it there if the attachment fails.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#540]
## Notes
The link included in the permit confirmation email (at least on staging) is:

`/christmas-trees/forests/8750fec3-9161-4748-96d0-18ac0e3863a5/applications/permits/false?t=arp`

## Acceptance Criteria
- [ ] The permit url should link to the purchesed permit

## Tasks
- [ ] Revisit whether the token query parameter is necessary to view the permit
- [ ] The permit url should have the form: `/christmas-trees/forests/:forestAbbr/applications/permits/:permitId?t=:token OR sans the token if not necessary
- [ ] PO approved.

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
hmmmmm, I just tested this on staging and the link looks correct. @ASprinkle do you want to confirm as well, and if it is ok I will close the issue.

**Comment by carlsonem** [comment]
@ASprinkle Can you please confirm this is working properly

**Comment by ASprinkle** [comment]
@davemcorwin @carlsonem 
As a side note: upon attempting to log in to the Open Forest staging site to test this, I was prompted to log in through login.gov.
Once logged in, and viewing the Christmas tree staging landing page, I did not see the admin functions.
![image](https://user-images.githubusercontent.com/33435621/55891241-1136ab80-5b69-11e9-99ef-23eb9c46a98f.png)

Since the ARP was already set up in staging for purchasing permits, I used the ARP page.

The email I received had this link: •	Your permit is available for printing from https://open-forest-staging.app.cloud.gov/christmas-trees/forests/arp/applications/permits/e32756a6-db00-4746-8c27-3115a3a8440d?t=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoiZTMyNzU2YTYtZGIwMC00NzQ2LThjMjctMzExNWEzYTg0NDBkIiwiaWF0IjoxNTU0OTA5NTk0LCJhdWQiOiJmcy10cmVlcy1wZXJtaXQtYXBpLXVzZXJzIiwiaXNzIjoidHJlZXMtcGVybWl0LWFwaSIsInN1YiI6ImNocmlzdG1hcyB0cmVlIHBlcm1pdCBvcmRlcnMifQ.GXXuBHi1adRoXWOtBN6FjeL4VGFh_sNzs4j6b2xxnnU or in an attachment to this email.

When I clicked on it, It took me to the page where I can choose to print my permit
![image](https://user-images.githubusercontent.com/33435621/55891596-adf94900-5b69-11e9-8b6e-b0c5561ff69e.png)

In the end, the link worked. No issues.

**Comment by davemcorwin** [comment]
This appears to work correctly.

**Comment by ASprinkle** [comment]
@davemcorwin While the URL links correctly - does it meet the tasks descriptions above? Can you check the task boxes or edit them to show that it is no longer needed? I'll check PO

Also, are we closing issues, or moving them to DONE and then adding them to a report - we were doing that with Andrew - not sure if we're still doing that. @MelissaBraxton

**Comment by davemcorwin** [comment]
@ASprinkle updated the tasks to be more accurate.
