### ISSUE TITLE
[Spike] Revisit the use and user experience of the `token` for verifying access to a permit

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#541]
## Notes
- Currently we only verify that the token is valid NOT that is matches the permit id requested
- When an invalid token is provided, the user interface does not communicate this to the user (see screenshot from staging)
- What is the value of this token???

![Screen Shot 2019-02-07 at 9.25.33 PM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/4ec44a01-19a6-49c9-b49a-190577236184)

## Acceptance Criteria
- [x] we know the value of the token.
- [x] we know whether or not we actually need to use it.

## Tasks
- [x] Obtain token (api) documentation from pay.gov. (Aaron to help with request)
- [x] PO approved.

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
Blocked/waiting on Pay.gov documentation

**Comment by davemcorwin** [comment]
documentation has been received: https://drive.google.com/drive/u/0/folders/1IyPHKBLvc8VNrVXpLDol7bTKryuaDU6E

**Comment by davemcorwin** [comment]
The current process creates a JSON Web Token ([JWT](https://jwt.io/introduction/)) (A signed token (using a secret) that contains the permit Id) for use when fetching a permit.

This is used in 3 places:

1. Passed to Paygov as part of the return url to use when redirecting the user after submitting a payment on Pay.gov

2. When fetching a permit from the api which happens
    - immediately after #1 above
    - when a user clicks on the permit link that is emailed to them

3. When "completing" a permit in the api which happens immediately after #1 above. 

It it not required by Paygov for anything.

The current implementation verifies that the JWT is valid, but does not use the permit id stored within, implying that any user's JWT would "authenticate" the access of any permit. All urls that require the JWT, also require the permit id, which is implemented as a uuid string that is not guessable (Ex. `06ce636a-ea22-49cb-a146-1af42bb9d4bd`) 

This is not the typical use case for JWT, nor are we actually using it to identify the permit. While there are no current issues with the application, I am questioning the purpose of using it here in addition to the non-guessable permit id. Access to the permits is public provided the correct url/permit id/jwt is known.

It was added in [commit](https://github.com/nciinc/fs-permit-platform/pull/252/commits/fe43198830ebe956ec21093964b0ec6c9c0ee209#diff-7fef9003aeac9f0f9c8b23ceec31aac6) in [PR](https://github.com/nciinc/fs-permit-platform/pull/252) but I can't find any discussion around why.

I'm wondering:
- can anyone remember or dig up any context around this?
- what, if any, security benefits this has
- should we remove it to eliminate unnecessary complexity

**Comment by davemcorwin** [comment]
@mtlaney @aaronburk Do either of you have any thoughts on this?

**Comment by mtlaney** [comment]
@davemcorwin I'm good removing any instance of JWT not being either utilized or utilized incorrectly

**Comment by carlsonem** [comment]
Decision was made to remove
