### ISSUE TITLE
As a Forest Service Open Forest Administrator for the Christmas tree platform I want to be prompted to authenticate through eAuth and I only want to see Christmas tree related information, so that I am not confused with Special Uses information.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#548]
## Notes
When attempting to log into the Christmas tree side of Open Forest I have been prompted to go through login.gov. Sometimes I can get around that by closing the window and restarting the process.  

When tested with a pilot forest FS Administrator for Christmas trees, they were confused when prompted to login.gov. They also had an option to "View Applications" for the Special Uses side which was confusing to them.  When the opted to log out of the admin page, they were taken to https://open-forest-staging.app.cloud.gov/mbs which created further confusion.

See word document with screen shots, attached below.
## Acceptance Criteria
- [x] A FS Christmas tree administrator is prompted to authenticate through eAuth, not login.gov when they access the admin site.
- [x] A FS Christmas tree administrator does not see Special Uses related information when they are logged in.
- [x] A FS Christmas tree administrator is directed to the logout page when they opt to log out.

## Tasks
- [x] PO approved.

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Screen shots of the FS Christmas tree administrator flow with login.gov/SU bug 
[OF Admin Prodcution XmasTree LoginBug.docx](https://github.com/18F/fs-open-forest-platform/files/2861865/OF.Admin.Prodcution.XmasTree.LoginBug.docx)

**Comment by ASprinkle** [comment]
@mtlaney here are some Forest Service employees who should already be white listed to access Christmas trees admin through eAuth:
 - Mt. Hood Jason Page jasonpage@fs.fed.us
 - Arapaho Roosevelt Tammy Williams tjwilliams@fs.fed.us
 - Shoshone Paul Rau prau@fs.fed.us
 - Flathead Tamara Kerr tkerr@fs.fed.us

I can send you more names if you need them, but thought this would be a helpful check point at least.

**Comment by mtlaney** [comment]
@ASprinkle 
The more I dig into this I realize the more clarification I need based on the way it is currently setup.

My understanding is, login.gov should only be used for regular users for outfitter permits and not used for admins and no login is used for christmas tree permits at all.

Eauth should validate all the admin paths. 
View Applications should only be available on the special uses side of the application. 
Who should view applications be available to on the special uses side though? Is it for users to view their applications, or admins to view all applications?

Also I don't see any login as admin option anywhere on the front end, it appears it's only logging in as admin if we hit one of the admin routes. Login Component is only handling login.gov for users and not admins. Is this intended or should we add a login as admin option?

**Comment by ASprinkle** [comment]
@mtlaney 

You're correct: login.gov should only be used for [the public] regular users for outfitter permits and not used for [the forest service] admins 

You're correct eAuth should validate access for Forest service admins for Open Forest.
You're correct "View Applications" is a special uses function - and should only be viewable on the special uses side.

Good question on View Applications, the answer is two-fold:
There is a function for the applicant to view a list of the applications they have submitted and their respective status.  When logged in through login.gov as an applicant, the top right hand corner says "Welcome" with the applicants email, and the option to "view applications" which should be only their applications that they have submitted.

![image](https://user-images.githubusercontent.com/33435621/53355378-b9f0ba80-38dd-11e9-8dd4-416f31a49aaa.png)

All of the applications in this list, are ones that I created when testing the site as an applicant.
![image](https://user-images.githubusercontent.com/33435621/53355500-fb816580-38dd-11e9-8c8b-e6512c343ecd.png)

There is also a function for the forest service administrator to view a list of all the applications that have been submitted to their forest, indicated by "Welcome admin amber sprinkle" in the top corner.
![image](https://user-images.githubusercontent.com/33435621/53354820-7e092580-38dc-11e9-96dc-4059bb343c4b.png)

For Administrator log in - good question. For the Christmas trees pilot, we had a separate URL for FS Administrators to log in with.  This way the landing page wasn't confusing to a member of the public.  Perhaps we maintain that same process for purposes of MVP and launching the pilot for the MBS.  We should ask @aaronburk  what his thoughts are on this one.

**Comment by carlsonem** [comment]
Blocked by #382

**Comment by ASprinkle** [comment]
Navigating to Open Forest Christmas tree for admins on the Staging site:
EAuth prompt 
![image](https://user-images.githubusercontent.com/33435621/56153983-49285f00-5f6c-11e9-9b16-5a6516ec4315.png)
