### ISSUE TITLE
As an administrator I want the permit purchase date to be consistent in the back end so that we aren't confused about when a permit was issued.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#550]
## Notes
Currently, we use the `updated` datetime of a permit to indicate the purchase datetime of a permit for reporting purposes. Since the `updated` field is automatically updated whenever there is a database change to the permit, this will only reflect the correct purchase datetime so long as no additional updates are made to the permit in the database.

We should create an additional column in the permit table to specifically maintain the datetime of purchase.

## Acceptance Criteria
- [x] Stored data reflects the correct purchase date of a permit regardless of other updates to the permit in the database.

## Tasks
- [x] Create a new timestamp column in the permit table for the purchase date.
- [x] Update relevant code to use the new column
- [x] Update seeders/factories to use the new column
- [x] Migrate the updated time to the new column before deploying to Staging and Production
- [x] PO approved.

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [x] Compare finished design with mockup
- [] Usability tested
- [x] End to end test

**Comment by ASprinkle** [comment]
This story likely has a design piece to it as it may impact the display of the Report Generated table.

**Comment by ASprinkle** [comment]
from stand up: may need to create some test case stories - usability testing for this issue.

**Comment by ASprinkle** [comment]
from planning: we need to create an issue for refactoring some of the tests to cover the new ‘purchaseDate’ field.

**Comment by briandavidson** [comment]
@ASprinkle this is deployed to staging and ready for you to take a look at.
