### ISSUE TITLE
As an admin I want to be able to see what happens in NRM test or NRM dev when an application is submitted to SUDS so that I can make sure tests are working.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#552]
## Notes
When we submit an application from Open Forest to SUDS, we should be able to access SUDS to test through the workflow.

## Acceptance Criteria
- [ ] We know who has access to NRM Dev.
- [ ] We understand how to navigate NRM Dev/SUDS to be able to confirm applications are successfully being transferred.

## Tasks
- [ ] 

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
@ASprinkle What is the goal here, is it for you to be able to access SUDS or for others? I think its probably a good idea to see who else has access to this environment...

**Comment by ASprinkle** [comment]
@davemcorwin good question.... 

Agreed, we confirm which of us is on the list to access NRM Dev.

"I want to be able to see what happens in NRM when an application is submitted".  Given the short amount of work that we did together testing NRM Dev SUDS Application feature, I think we have verified that we can see what happens after fumbling through figuring out which application to select and how to query the database.

Perhaps This should be rephrased (split into other stories) for
-Knowing how to search for applications
-The expectation is that the Forest Service administrator would be able to complete the application/review/authorization in SUDS based on the information that transfers over.
-We should verify that all the information is transferring correctly from Open Forest

**Comment by ASprinkle** [comment]
@aaronburk @carlsonem  Can you add a story to the Trello Board about SUDS.  This story may be more applicable to Trello vs. Production.

**Comment by ASprinkle** [comment]
@davemcorwin I am closing this issue because since I created this store, we have confirmed that we can see information transferring into NRM Dev from Open Forest when an application is approved in Open Forest.  
Trello board should capture tasks associated with assigning team member roles to SUDS.
