### ISSUE TITLE
As a Developer/administrator I want consistent, useful logging

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#559]
## Notes
Current logging is haphazard and inconsistent. Logging should be implemented as middleware to ease developer burden and maintain consistency.

## Acceptance Criteria
- [ ] Logging is consistent and helpful
- [ ] No observable changes in functionality

## Tasks
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
Stories in the Program board may be addressing this story. As those stories are completed, we will need to review this to see if this is still a need.

**Comment by mwreiss** [comment]
Please reference #70 on the program board https://code.fs.usda.gov/NFS/Open-Forest-Program/issues/70.  Some or most of this one should be covered.
