### ISSUE TITLE
Special Use Form Date picker

### ISSUE THREAD

**Issue by DawnDesigner** [18F/fs-open-forest-platform#563]
## Notes
* As a user I would like to be able to select a date from a calendar popup so that I make fewer mistakes when entering a date in the application *

## Acceptance Criteria
- [ ] I would like to see a calendar pop up so I can easily pick it
- [ ] Needs to be 508 compliant 
- [ ] I would like to see that date displayed after I pick it
- [ ] I would like to have the opportunity to choose beginning and ending dates where applicable
- [ ] I would like to be able to begin typing a date and the calendar pops up
- [ ] I would like to be able to clear the dates if I want to start over

Source request:  Special Use User Testing - Results and Insights – Non-Commercial themes
“Many participants would prefer a calendar picker or selector drop in the current fields to fill in for their trip dates.  “No drop down? You’re killing me.  I put things in wrong all the time.” Or “It would be cool if a calendar popped up.”

Reference stories #395, and this could solve issues in story #468 

## Tasks
- [ ] Make sure chosen date picker is 508 compliant
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
![Date Picker Mocked up](https://user-images.githubusercontent.com/47989077/54229522-d0e8fc80-44da-11e9-8027-869117f38055.png)

**Comment by DawnDesigner** [comment]
This story is now PO approved (Amber) and ready for development

**Comment by MelissaBraxton** [comment]
This is exciting!  If we do develop an accessible calendar date picker, then we should add a task to include it in the style guide:  https://nciinc.github.io/fs-fork-uswds-site/components/form-controls/#date-input


I have a question out to the USWDS folks about why they only recommend a text input date picker.

**Comment by carlsonem** [comment]
Missing the screen reader option from the existing EAD calendar. @DawnDesigner to work with @mtlaney to find a solution

**Comment by DawnDesigner** [comment]
Possible solution:
The biggest complaint from the users is that the current date form doesn't format or help them with typing.  So, can we consider updating the input box to have auto formatting something like this:

https://webdesign.tutsplus.com/tutorials/auto-formatting-input-value--cms-26745

Second: Would it be possible to provide this type of input field (like the existing one with auto formatting) and place a calendar icon next to it that allows a user to either type it manually (508) or click on the calendar picker. Ideally both would populate the same input field. Don't know if that's possible to build in our stack.  

I have seen this same idea on a site recently (can't remember where) and it worked nicely.  This might give everyone what they want.

Thanks

**Comment by DawnDesigner** [comment]
@MelissaBraxton  @mtlaney  @davemcorwin  At a recent government UX Summit I attended a session about usability and the presenter tells me she has a 508 tested and approved date picker.  She gave me the contact info as the source and I will be providing that information for this team as soon as I hear back. We'll see if it works in our environment. Fingers crossed.

By the way, she did also say my solution above would work and acceptable. It is in compliance with option to offer two solutions - one for those using assistive technology, and those not.  

I'll leave it up to the development to choose - if the picker is usable I'm thinking that would be best case scenario.

**Comment by lisamcmichael** [comment]
Design refinements are needed; Amber to refine story as well

**Comment by ASprinkle** [comment]
@lisamcmichael I updated the A/C and Tasks (minimally)

**Comment by ASprinkle** [comment]
We learned from SPIKE #981 that we will not be able to build a 508 compliant calendar pop up into the SU system in time for MVP Dec. We are keeping this story in the icebox so that we can build this feature later.
