### ISSUE TITLE
Email daily snyk reports to USDA Security

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#572]
## Notes
As a security organization, I want to receive Snyk vulnerability analysis reports via email.

## Acceptance Criteria
- [x] Security folks receive the daily Snyk vulnerability analyses via email.

## Tasks
- [x] Add staging and production configuration for email addresses to receive these emails to the user provided smtp-service key in `platform-staging` and `platform-production` respectively. (See below for example)
- [x] Create a snyk email script using `nodemailer` dependencies to email the most recent snyk report to configured email addresses
- [x] Add an entry in the npm scripts to run the snyk email script
- [x] Append a step to the `nightly-snyk` CircleCI workflow to run the above script using [Cloud Foundry Tasks](https://docs.cloudfoundry.org/devguide/using-tasks.html)
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [x] Compare finished design with mockup
- [x] Usability tested

### Snyk configuration
```
{
  ...
  "credentials": {
    ...
    "snyk": [
      "pburckhardt@fs.fed.us",
      "hieunguyen@fs.fed.us"
    ],
    ...
  }
  ...
}
```

**Comment by davemcorwin** [comment]
This won't be marked as complete until this is verified in production.

**Comment by aaronburk** [comment]
I approve merge in Prod
