### ISSUE TITLE
As a user I want Open Forest to function normally when using an ad blocker

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#578]
## Notes
Some ad blockers may block our analytics service from loading on the page, but the application assumes it is always present and crashes when it is not.

## Acceptance Criteria
- [x] Open Forest functions normally when analytics is blocked by an ad blocker.

## Tasks
- [x] Ensure analytics service is available before attempting to use it.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

## Context
Originally reported by @suprenant using the `uBlock Origin` extension in Chrome.

![Screen Shot 2019-04-03 at 12.11.06 PM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/59b1c5d1-a4d3-4f59-b1c2-10c75b261db8)
