### ISSUE TITLE
Upgrade Docker Angular CLI

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-open-forest-platform#581]
## Notes
As a Developer I would like Dockers Angular CLI version to match the actual application

## Acceptance Criteria
- [x] Dockers Angular CLI version matches

## Tasks
- [x] Upgrade Docker's Angular CLI Version

## Definition of Done
- [x] Docker Frontend file updated
- [ ] Reviewed by an additional developer
- [ ] Passes Docker install and tests

**Comment by aaronburk** [comment]
I approve.  I did some checks in staging, we will review again in prod
