### ISSUE TITLE
As a user, when I log out of Open Forest, I would also like to terminate my eAuth or Login.gov session for security reasons

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-open-forest-platform#595]
## Notes
When logging out of the application, I would like to be also logged out of the Authentication system I connected with (Login.gov / eAuth). 

## Acceptance Criteria
- [x] Logging out as a user will also log me out of Login.gov
- [] Logging out as an admin will also log me out of eAuth
- [x] Logging out as either will remove my user in localstorage

## Tasks
- [x] Trigger passport.js logout methods via frontend
- [x] After logging out, redirect to home page for that section
- [x] PO Approved

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [x] Passes all circle tests
- [x] PO reviewed and approved
- [x] Usability tested
- [x] Reviewed by someone other than the original author

**Comment by ASprinkle** [comment]
@davemcorwin When I tested this on staging - Christmas tree admin site, I was able to log out with out issue 
![image](https://user-images.githubusercontent.com/33435621/56429273-2d2c0280-6277-11e9-9645-bc1fe9831cd9.png)

When I attempted to log in to the Open Forest Special Uses site, I was prompted to login though Login.gov.  I had to use the incognito window to log in to the https://open-forest-staging.app.cloud.gov/admin/applications though eAuth staging

**Comment by davemcorwin** [comment]
@ASprinkle @mtlaney 
On staging, logging out of the admin area does NOT log out of EAuth, when logging back in I am NOT prompted to authenticate with EAuth.

Everything else looks good.

**Comment by ASprinkle** [comment]
Ok thank you Dave - have we determined that we cannot log out of eAuth when we select the "log out" button in the admin screen?  If so, then we should inactivate the AC criteria that says "Logging out as an admin will also log me out of eAuth" if that is something we cannot do.

**Comment by davemcorwin** [comment]
I'm fairly certain that we CAN do it, but it is currently not happening.
