### ISSUE TITLE
As a developer I don't want dependency vulnerabilities to prevent code from being merged into `dev`

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#597]
## Notes
As part of our continuous integration process, each branch/pull requests must pass our depenedency analysis check before being merged into `dev`. Vulnerabilities from EXISTING dependencies may arise multiple times a week causing delays in the workflow for EVERY outstanding pull request. While it is important to be aware of and address vulnerabilities quickly, this should only affect DEPLOYED code and has become overburdensome. 

I recommend we do NOT run Snyk as part of every branch, while continuing to run it for the `staging-deploy` step so individual PRs are not held up and any necessary remediation for staging deployment can be handled in a separate pull request.

cc @mtlaney 

## Acceptance Criteria
- [x] Snyk dependency analysis check should NOT be required to merge pull requests into `dev`
- [x] Snyk dependency analysis check should still be required to deploy `dev` to `staging`
- [x] No other changes

## Tasks
- [x] Move `snyk` to a separate job in the CircleCI configuration
- [x] Do not run `snyk` job for every branch
- [x] Ensure `snyk` job IS run for `staging-deploy`, `prod-deploy`, nightly, etc.
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [x] Usability tested

**Comment by ASprinkle** [comment]
@davemcorwin  Because of this story's technical nature, it is hard for me to review this.  Can you check the AC and Task boxes that have been completed? If I thought there would be time next week, I would coordinate a walk through/discussion with you. But I do not want my schedule to slow things down.
Once the AC and Task boxes are selected, I will check for PO.

**Comment by davemcorwin** [comment]
@ASprinkle I checked some boxes. This only affects our continuous integration pipeline so as long as you can verify that nothing is broken on the app I think we are good.
