### ISSUE TITLE
As a developer I want to resolve vulnerabilities due to an outdated dependency

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#598]
## Notes
Upgrade to Sequelize v5 to resolve dependency vulnerability

```
✗ Medium severity vulnerability found in sequelize
  Description: SQL Injection
  Info: https://snyk.io/vuln/SNYK-JS-SEQUELIZE-174167
  Introduced through: sequelize@4.42.0
  From: sequelize@4.42.0
  Remediation: 
    Upgrade direct dependency sequelize@4.42.0 to sequelize@5.3.0 (triggers upgrades to sequelize@5.3.0)

```
## Acceptance Criteria
- [x] No changes

## Tasks
- [x] Upgrade to Sequelize v5 - Platform
- [x] Upgrade to Sequelize v5 - Middlelayer
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [x] Compare finished design with mockup
- [ ] Usability tested
