### ISSUE TITLE
As a user I want to be prevented from entering an invalid email address

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#600]
## Notes
The current client-side email address validation is incorrect allowing invalid addresses such as `aaa@aaa`, in addition, certain email fields in the database to not include email address validation. Update the regular expression used to validate the email address to be correct and add validation to database email fields where it is missing.

## Acceptance Criteria
- [x] `aaa@aa` is "invalid"
- [x] An error note displays when verification field data is missing
- [x] An error note displays when verification data does not match
- [x] An error note displays when an invalid email address is used, with hint text for what is acceptable
- [x] no other changes

## Tasks
- [x] Update client-side regular expression to correctly validate email addresses
- [x] Add "email" validation to the database fields where it is missing
- [x] update for scenario 3 (in the comments)
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
@davemcorwin I'm not completely familiar with sequilize, but let me know if the below code is kind of what we're looking for on server side email validation as a back up.

`    applicantInfoEmailAddress: {
      type: Sequelize.STRING(255),
      field: 'applicant_info_email_address',
      allowNull: false,
      validate: {
        is: {
          args: [^[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$],
          msg: 'applicantInfoEmailAddress must be a valid email address',
        len: {
          args: [1, 255],
          msg: 'applicantInfoEmailAddress must be less than 255 characters in length'
        },
        isEmail: true
      }
    },
`

**Comment by davemcorwin** [comment]
The email validation is added by the `isEmail: true` so the regex is not necessary. See https://github.com/18F/fs-open-forest-platform/blob/dev/server/src/models/noncommercial-application.es6#L218 for an example.

**Comment by ASprinkle** [comment]
In testing on Staging:

I entered my email address, and then entered it again so that it didn't match. The error was good, and did not let me continue through to the purchase process.
![image](https://user-images.githubusercontent.com/33435621/57404262-6aa5f080-7190-11e9-832c-3caa3267c7c1.png)

I entered an email address in to test the "valid" email address aspect of the story, and it appeared to allow me to continue with this information
![image](https://user-images.githubusercontent.com/33435621/57404334-91fcbd80-7190-11e9-88dc-4883d7ec7572.png)

I tested it a third time using asprink@no and entering it the same in both fields.  While I was not able to continue, and there was a red information box that populated telling me to correct my errors, and the email boxes highlighted in red, there was no hint text telling me what my error was.
![image](https://user-images.githubusercontent.com/33435621/57404480-e7d16580-7190-11e9-9264-65fc6fa3ab81.png)

**Comment by ASprinkle** [comment]
In Scenario 2 it looks like an invalid email address can still be entered.  Perhaps that is because it appears to follow the schema for valid email address something@something.something. 

In Scenario 3 where the email address is something@something we should have hint text that tells the user to enter a valid email address, just like in scenario 4, correct?

**Comment by davemcorwin** [comment]
@ASprinkle Thanks for checking these different scenarios. The ones we are focused on with this issue are 2, 3, and 4 since we are addressing the validity of each email address, not whether they match, though it is good to make sure we don't break anything.

In this case a "valid" email is one that matches the specification for what an email address can look like, NOT whether that email address actually exists. There is no way to know if it exists until we actually send an email, so the only scenario highlighting an issue here is  #3. There should definitely be an error message present on the email fields themselves @mtlaney .

**Comment by mtlaney** [comment]
@ASprinkle @davemcorwin  You are both correct, scenario 3 should display the same hint text as scenario 4, I'll check it out.

**Comment by ASprinkle** [comment]
The error texts appears to be populating correctly.

![image](https://user-images.githubusercontent.com/33435621/58268612-930a1f00-7d3a-11e9-952b-dab6ecbbdb42.png)

**Comment by ASprinkle** [comment]
@mtlaney While, this story is ready for master, I may need to create another one to address the following error.  I was able to recreate it several times.

![image](https://user-images.githubusercontent.com/33435621/58268677-b765fb80-7d3a-11e9-9af9-46733e765076.png)

![image](https://user-images.githubusercontent.com/33435621/58268802-fe53f100-7d3a-11e9-8bd2-3cb015e2e1a2.png)


It seems like this error shouldn't mention a name and email requirement since those fields are entered. It goes away when I check the box.
![image](https://user-images.githubusercontent.com/33435621/58268723-d5336080-7d3a-11e9-806b-35001afe1dfb.png)

**Comment by davemcorwin** [comment]
@ASprinkle There is no error here. The presence of that error message is correct, its referring to consenting to our collection of name and email... That said, the content could be rephrased a bit.

**Comment by ASprinkle** [comment]
@davemcorwin Ah, ok! that makes sense.  I suppose I only glanced at it, saw the name and email bit, and thought it was a name and email error - Which is probably what most people would do instead of actually reading it!  We'll need to shorten that up quite a bit. It use to be something else I  believe; much shorter. Not sure why it changed.
