### ISSUE TITLE
[SPIKE] As an admin I want to submit a special uses application to SUDS (staging)

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#601]
## Notes
When accepting an application in the admin interface, an error occurs when sending the application to SUDS. It is unclear if the cause is due to the platform, middleware, or development SUDS configuration. This is observed in the `staging` environment, it is not certain whether this is an issue in production.

## Acceptance Criteria
- [x] An admin can submit an application to SUDS in `staging`
- [x] We have an understanding of how applications with applicants who have the same name and different addresses can be transferred to SUDS from Open Forest.
- [x] We have and understanding of how applications with the same address and different names can be transferred to SUDS from Open Forest.

## Tasks
- [x] Identify the cause of the issue
- [x] Identify next steps to resolve the issue
-[] Fix the issue (TBD)
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
Error in staging when attempting to authenticate with SUDS:
```
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "level": "error",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "message": "ERROR: ServerError: Controller- Error: certificate has expired in auth.getToken controller",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "timestamp": "2019-04-15T23:12:04.403Z"
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR }
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR {
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "message": "ERROR: ServerError:",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "name": "RequestError",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "cause": {
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "code": "CERT_HAS_EXPIRED"
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   },
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "error": {
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "$ref": "$[\"cause\"]"
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   },
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "options": {
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "auth": {
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR       "user": "sudsws",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR       "pass": "ePerm!ts",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR       "sendImmediately": true
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     },
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "json": true,
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "uri": "https://nrmwebdev1.fs.usda.gov:8443/sudsws/api/login",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "method": "POST",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "simple": true,
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "resolveWithFullResponse": false,
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR     "transform2xxOnly": false
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   },
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "stack": "RequestError: Error: certificate has expired\n    at new RequestError (/home/vcap/deps/0/node_modules/request-promise-core/lib/errors.js:14:15)\n    at Request.plumbing.callback (/home/vcap/deps/0/node_modules/request-promise-core/lib/plumbing.js:87:29)\n    at Request.RP$callback [as _callback] (/home/vcap/deps/0/node_modules/request-promise-core/lib/plumbing.js:46:31)\n    at self.callback (/home/vcap/deps/0/node_modules/request/request.js:185:22)\n    at emitOne (events.js:116:13)\n    at Request.emit (events.js:211:7)\n    at Request.onRequestError (/home/vcap/deps/0/node_modules/request/request.js:881:8)\n    at emitOne (events.js:116:13)\n    at ClientRequest.emit (events.js:211:7)\n    at ClientRequest.wrapped (/home/vcap/deps/0/node_modules/newrelic/lib/transaction/tracer/index.js:181:22)\n    at ClientRequest.wrappedRequestEmit (/home/vcap/deps/0/node_modules/newrelic/lib/instrumentation/core/http-outbound.js:146:26)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)\n    at emitOne (events.js:116:13)\n    at TLSSocket.emit (events.js:211:7)\n    at Shim.applySegment (/home/vcap/deps/0/node_modules/newrelic/lib/shim/shim.js:1396:20)\n    at TLSSocket.wrapper [as emit] (/home/vcap/deps/0/node_modules/newrelic/lib/shim/shim.js:2020:17)\n    at emitErrorNT (internal/streams/destroy.js:66:8)\n    at Shim.applySegment (/home/vcap/deps/0/node_modules/newrelic/lib/shim/shim.js:1396:20)\n    at wrapper (/home/vcap/deps/0/node_modules/newrelic/lib/shim/shim.js:2020:17)\n    at _combinedTickCallback (internal/process/next_tick.js:139:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:219:9)\n    at process.wrappedProcess (/home/vcap/deps/0/node_modules/newrelic/lib/instrumentation/core/timers.js:15:21)",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "level": "error",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "timestamp": "2019-04-15T23:12:04.403Z"
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR }
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR {
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "level": "error",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "message": "ERROR: ServerError: / POST unable to process request.",
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR   "timestamp": "2019-04-15T23:12:04.404Z"
   2019-04-15T16:12:04.40-0700 [APP/PROC/WEB/0] ERR }
```

**Comment by davemcorwin** [comment]
@ASprinkle @aaronburk 
I believe the error here results from an assumption that we make when interacting with SUDS. Before submitting the application, we check to see if the contact person for the application exists in SUDS, if so, we send over the application, if not, we create the contact in SUDS.

SUDS requires that for an application, the contact exists AND has an address. In this case, the contact exists so Open Forest sends over the application, but the contact DOES NOT have an address, causing SUDS to throw an error.

1) If its necessary AND we don't mind the extra request, Open Forest can be a bit smarter here and actually check if an address exists and sending one over if necessary.

2) We should test to see how we are determining uniqueness here, hopefully its by more than just name...

**Comment by aaronburk** [comment]
Likely a research spike is needed with Lisa and Dawn and Jennifer

**Comment by ASprinkle** [comment]
Updated story to reference as a SPIKE.  Initially research with Dave and Amber, potential for Lisa and Dawn to participate if research indicates potential design and user interface needs.

**Comment by ASprinkle** [comment]
@davemcorwin I have been having some trouble getting into NRM Dev to test the number of spectators through the application into authorization function...  Hopefully I can get in today and test it out.

![image](https://user-images.githubusercontent.com/33435621/57028087-049af580-6bf3-11e9-9dac-6add13940d28.png)

**Comment by ASprinkle** [comment]
I have been informed that NRM Dev is currently down. I will not be able to test this to complete the story until NRM Dev is back up and running.

**Comment by ASprinkle** [comment]
Amber scheduled time 5/8 to work on this.

**Comment by ASprinkle** [comment]
NRM is back up and running at this point. But I am having issues logging into Open Forest admin site to check for address, names, and submitting applications to SUDS...

**Comment by davemcorwin** [comment]
NRM Dev and our staging? Feel free to ping me with the issues logging into staging.

**Comment by ASprinkle** [comment]
eAuth cert environment - need to confirm issues there

**Comment by ASprinkle** [comment]
[SUSDS Spike documentation Zenhub 601.docx](https://github.com/18F/fs-open-forest-platform/files/3183637/SUSDS.Spike.documentation.Zenhub.601.docx)

**Comment by ASprinkle** [comment]
Results in Brief:

SUDS Accepts applications regardless of whether or not information already exists in the system.
SUDS can have multiple names and same addresses without issue
If coming from Open Forest, SUDS can only have One Name associated with an address.  Same Name applicants with different addresses may be an issue.

SUDS has a unique identifier "Contact ID" that would resolve the issue of Same Name applicants from Open Forest. When an application is sent to SUDS from Open Forest, the application has an "Application ID", but the Contact ID is automatically populated to be the Last Name, First Name of the applicant.

Open Forest should send the Applicant contact information to SUDS with a unique contact ID number so that same name applicants do not encounter problems with their application process, and so that FS administrators do not have to query an applicants name manually before they "submit to SUDS" from Open Forest.

When I Manually Entered the Scenario 1 (in attached doc above) Name and Address as a new record in SUDS. SUDS applied a different Contact ID to my manual entry automatically.  When I queried last name %NAME% both "Same Names" populated but with different contact IDs associated.  The SUDS manual entry has a numeric value, the Open Forest automatic entry has the Last Name, First Name as the value.

**Comment by ASprinkle** [comment]
If we create a story for Open Forest to generate a unique contact ID number to populate SUDS (Assuming it does not repeat one that already exists in SUDS) is that something we can accomplish?

OR is there a way for the contact information to go from Open Forest to SUDS without a Contact ID field and let SUDS auto populate that field when the SU Admin goes in to "accept" the application in SUDS?

**Comment by davemcorwin** [comment]
@ASprinkle thanks for looking into this! I believe the solution would involve maintaining a unique list of users on our end and associating each of those users with an appropriate, unique SUDS identifier for the contact on their end. We are going to let SUDS generate their own identifier for contacts. This isn't perfect in that we won't be able to prevent duplicates in SUDS for contacts that exist before they become users of Open Forest. The alternative is a more interactive experience for Open Forest users where if their name matches a SUDS contact, we give them the opportunity to identify whether it is them or not, perhaps even updating the address in SUDS. This is definitely more work.

I suggest a we schedule some time to chat about this in detail, identify our desired outcomes and prioritize the work.

**Comment by ASprinkle** [comment]
Notes from meeting 5/23- 
@davemcorwin will look to see if Open Forest is sending the Contact ID information to SUDS,
and confirm whether or not SUDS is doing in response to what Open Forest is sending.

Shadat will coordinate with an NRM/SUDS POC to find out how SUDS was meant to work with Open Forest.

The same name/contact id issue must be resolved prior to MBS pilot launch.

**Comment by davemcorwin** [comment]
## Notes
It looks like we **OF** flows for when the contact is a "person" or an "organization". The difference is the contact id for an organization is the organization name, whereas for a person it is `lastname,firstname`.

## Findings
- The current flow is the following:
  - **OF** queries **SUDS** contacts by last name
  - **OF** filters the **SUDS** contacts by contact id
  - If there are no matches, **OF** sends to **SUDS**
    - contact 
    - contact address
    - contact phone
  - If there are multiple matches **OF** throws an error
  - If there is a single match, **OF** sends to **SUDS** the application
- I think that we are generating the contact id and sending it to **SUDS** when creating a contact

## Questions

- Is it possible that the contact control number is the unique identifier that **SUDS** uses to identify a contact?
- Are there legacy requirements that drove these decisions? Ex. are we trying to leverage contacts (people and organizations) that are already exist in SUDS instead of creating new ones for **OF**?
- Are there any character restrictions in play that would prevent us from using email address as the contact id for a person? (organization name is probably fine for organizations)

**Comment by davemcorwin** [comment]
SUDS confirmed that the "contact contract number" is assigned by SUDS and unique. It is not believed that we can use email address instead of "lastname, firstname" in the contact id field due to a 30 byte limit on the field.

Shadat scheduled another follow up with SUDS folks after our meeting today. They will confirm:
- we can't use an email address in the contact id field
- what other options we have for uniqueness, such as full name + phone number
- the SUDS API endpoints available to use
