### ISSUE TITLE
As a special uses applicant I want to be able to successfully submit my application without an email character limit error.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#603]
## Notes
* What are things we should consider when making this story *
During the special uses platform demonstration, the application for noncommercial group use or temporary outfitter guide could not be submitted. An error note was received on the page stating that the email address had to be less than 255 characters.

## Acceptance Criteria
- [x] The application for both non commercial group use and temp outfitter guide can be submitted after it is completed.
- [x] The email notifications are correctly being sent to the applicant and the administrator.
- [x] The application and it's status is populated in the administration side of open forest.

## Tasks
- [] Needs DEV refinement.
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
@ASprinkle Can you
- include screenshots of the error (and anything else on the page that looks suspicious)?
- include screenshots of the javascript console? (I can help with this)

**Comment by ASprinkle** [comment]
@davemcorwin  I went through the process again:
Here are the screen shots
Non-Commercial Application
![image](https://user-images.githubusercontent.com/33435621/56168610-8e5e8800-5f90-11e9-8ed7-5cabd2fcd77d.png)

Sprint Screen of Temporary Outfitter Guide
![image](https://user-images.githubusercontent.com/33435621/56168757-f57c3c80-5f90-11e9-87c0-e814b89b78d5.png)
![image](https://user-images.githubusercontent.com/33435621/56168759-f7460000-5f90-11e9-9e9f-6c194178cc70.png)

**Comment by ASprinkle** [comment]
I was unable to check the admin side - getting 404...

**Comment by davemcorwin** [comment]
@ASprinkle 
1. Can you think of what changed since it did not work previously?
2. can you be more specific on the 404, what url?

**Comment by ASprinkle** [comment]
Looks like I am now able to get in to the MBS admin side without an issue.... 

I haven't been able to recreate the errors we saw during the demo... SO i think we can close this story - which is good news! (I think)
