### ISSUE TITLE
As an applicant I want to submit a non-commercial permit application when the data is valid and/or know the specific errors when the form won't submit, so that I know whether or not my application is successfully being submitted.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#605]
## Notes
On the non-comm form pages, the form does not submit and displays a generic error message, but there is no indication what field is causing the problem.

URL: `/mbs/applications/noncommercial-group-use/new`

- All fields look valid
- there are no console errors
- the `form` is marked `ng-valid`
- possibly `dateStatus.hasErrors` is true

![Screen Shot 2019-04-15 at 10.42.27 AM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/acd38c9d-3adc-4143-8323-a4842d2edf32)

## Acceptance Criteria
- [x] The form submits when data is valid

## Tasks
- [x] Fix the date time validation to correctly take into account am/pm
- [x] Add specific validation errors to the UI so users can understand and fix data entry errors in the date/time fields
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
1. The date validation in `date-time-range.component.ts` is incorrect and does not take into account am/pm when determining if start date is before end date
2. There is no detailed error message to indicate to the user what date time errors exist

Updating tasks....

**Comment by ASprinkle** [comment]
@davemcorwin I tested this in staging a few different ways.  Errors were clear, I was able to test the start times too, for different ranges, and the errors came back appropriately.  Applications were submitted for review successfully when all required fields were validated.
