### ISSUE TITLE
[SPIKE] As an applicant when I select a SU application and authenticate can login.gov redirect me to the preauthenticated URL (where I was when I started)

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#608]
## Notes
* What are things we should consider when making this story *

As an applicant - if I click on apply for a temporary permit from the MBS landing page, and go through login.gov, can I be directed to the temporary permit workflow, or do I have to come back to the MBS landing page?

Is login.gov restricted to one url or can login.gov host two url options (i.e., an option for temporary permit redirection, and an option for non-commercial permit redirection).

(Having a  better understanding of the capability of login.gov will help inform workflow and design for multiple other stories.)

## Acceptance Criteria
- [x] We understand whether or not login.gov can host more than one url.
- [x] We find out what next steps are needed.

## Tasks
 -[] Refine as we discuss with DEV
- [x] Meet with DEV to discuss this research spike.
- [x] DEV to follow up with login.gov
- [x] PO approved

## Definition of Done
- [ ] all tasks completed.

**Comment by davemcorwin** [comment]
When authenticating with Login.gov, we can specify the redirect url at the time we send the user there, so we have full control over where the user ends up after authenticating with Login.gov.

**Comment by lisaredux** [comment]
> When authenticating with Login.gov, we can specify the redirect url at the time we send the user there, so we have full control over where the user ends up after authenticating with Login.gov.

Thanks @davemcorwin . Now we @DawnDesigner @ASprinkle and I will decide on the best path moving forward and update here.

**Comment by ASprinkle** [comment]
We will need to refine the "Next Steps" before closing out this story...

**Comment by lisaredux** [comment]
@ASprinkle Makes sense... Here is some of the diagrams to start the conversation https://docs.google.com/presentation/d/1MzvE8QKD6JxStiYmFm8gCA1--8zR_vtuO5XrbF0fLRg/edit#slide=id.g50bf42e953_0_197

**Comment by ASprinkle** [comment]
@lisaredux Thank you for linking that document.  

Next steps:  plan on moving forward the concept in #3 from the document you linked, pending pairing with @davemcorwin and/or @mtlaney to begin crafting it.  
here's a screen shot
![image](https://user-images.githubusercontent.com/33435621/56444653-6df33e00-62ae-11e9-9db4-c9af3e00b63e.png)

Possibly refine the path after next week's meeting.  There does not appear to be a story specific to the development of this user flow at this point and that is ok - we can do more with this next week.
