### ISSUE TITLE
As a developer I want to develop against the CERT EAuth environment that does not require our staging or production environment.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#609]
## Acceptance Criteria
- [x] A developer can use to a CF environment that integrates with EAuth CERT environment

## Tasks
- [x] Create a 'dev' environment in Cloud.gov that integrates with EAuth CERT
- [x] Document this environment
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical defintion of done

**Comment by davemcorwin** [comment]
@ASprinkle I have added documentation and verified this works [here](https://open-forest-dev.app.cloud.gov/christmas-trees/forests/), there are no changes to the existing application.
