### ISSUE TITLE
As a developer I want to be able to test all authentication flows locally.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#613]
## Notes
Currently, we do not have a way to test EAuth authentication flows locally, this makes it difficult to alter these flows since we can't view the effects until the application is in the staging environment. The goal here is to create a mock flow that can be used in development.

Testing for the AC should involve checking public and authenticated areas of the application to make sure everything behaves as expected. No changes should be observable to the user.

## Acceptance Criteria
- [x] All authentication flows can be evaluated in a local development environment

## Tasks
- [x] Create a mock "eauth" service to be used in development
- [x] Add authentication tests where necessary
- [x] Update existing tests to use mock eauth service
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical defintion of done
- ~[] Compare finished design with mockup~
- [x] Usability tested

**Comment by ASprinkle** [comment]
@davemcorwin can you pleas check the task boxes (or minimize the inapplicable tasks) on this story so that I can easily see what's been done so far?

**Comment by davemcorwin** [comment]
@ASprinkle This is not ready for Awaiting Acceptance. I think we need to change something in Zenhub bc it looks like the creation (not merging) of a pull request caused this to move to Awaiting Acceptance.

**Comment by davemcorwin** [comment]
@ASprinkle I am aware and looking into in issue with Login.gov authentication, will update when I have a fix.

**Comment by davemcorwin** [comment]
@ASprinkle For this, we can just confirm that authentication flows are working as expected in staging.
