### ISSUE TITLE
As a Forest Service manager I want to have a clear understanding of the processes involved in issuing a Christmas tree permit through Open Forest so that I can make good decisions about future scale up possibilities.

### ISSUE THREAD

**Issue by lisaredux** [18F/fs-open-forest-platform#616]
## Notes
* A service design blueprint for Christmas trees permits — to capture all the dependencies and backstage actions that are inline with user actions  *

## Acceptance Criteria
- [x] We have a single detailed blue print (work flow)that includes the FS admin actions for issuing a Christmas tree permit through Open Forest, and the customer experience for obtaining a Christmas tree permit through Open Forest.
- [x] The blue print should be a shareable document that is easily to use and understand across lines of business.
- [x] The blue print has been validated by subject matter experts.

## Tasks
- [x] Work with PO and Aaron to identify subject matter experts
- [x] Recruit subject matter experts
- [x] Interview subject matter experts
- [x] Make the blueprint
- [x] Present the blueprint - make an interactive meeting to highlight areas of risk and opportunity
- [x] PO Approved

## Definition of Done
- [ ] Dev has input
- [ ] Product owner has input
- [ ] Team defines area of risks and opportunities

**Comment by lisaredux** [comment]
@ASprinkle checking to see if this is something we can take on for Sprint 1
background info:
[The difference between a journey map and a service blueprint](https://blog.practicalservicedesign.com/the-difference-between-a-journey-map-and-a-service-blueprint-31a6e24c4a6c)
[Service Blueprints - Communicating the Design of Services](https://www.interaction-design.org/literature/article/service-blueprints-communicating-the-design-of-services)

**Comment by lisaredux** [comment]
In progress: https://app.mural.co/t/gsa6/m/gsa6/1556304246045/9078126a0403e523b60577ef1a3da304df563a83

**Comment by ASprinkle** [comment]
Update from stand up: Lisa will begin work on this next week 6/17, after user testing for other stories is complete.

**Comment by lisaredux** [comment]
Thanks @ASprinkle. Thinking of when to schedule a demonstration. Do you think we might have time to present this at the end of standup on Friday, 6/14?

**Comment by lisaredux** [comment]
Demo walkthrough to larger group scheduled for 6/19 after daily-standup —closing out this story 6/19.

**Comment by ASprinkle** [comment]
https://teams.microsoft.com/_#/pdf/viewer/teams/https%3A~2F~2Fusdagcc.sharepoint.com~2Fsites~2Ffs-nfs-oft~2FShared%20Documents~2FGeneral~2FChrismas_trees_Service_Blueprint_v01-05132019.pdf?threadId=19%3Ab7a4442cf735475ca1477dd6d1eaea3a%40thread.skype&baseUrl=https%3A~2F~2Fusdagcc.sharepoint.com~2Fsites~2Ffs-nfs-oft&fileId=AC6563D5-20F0-46EF-932C-8DEB3411AD38&ctx=files&viewerAction=view

**Comment by ASprinkle** [comment]
Notes from presentation to team:  
future consideration are our system security plan as we scale up with additional products and gather information required for those product permits (i.e., huckleberry and mushrooms).

Heavy lift research needs should be directed upwards (SORN, Feedback tools, policy changes); team to identify needs for further research.

We have a good base, to begin to expand Open Forest.

**Comment by lisaredux** [comment]
> The blue print is saved here: https://teams.microsoft.com/_#/pdf/viewer/teams/https%3A~2F~2Fusdagcc.sharepoint.com~2Fsites~2Ffs-nfs-oft~2FShared%20Documents~2FGeneral~2FChrismas_trees_Service_Blueprint_v01-05132019.pdf?threadId=19%3Ab7a4442cf735475ca1477dd6d1eaea3a%40thread.skype&baseUrl=https%3A~2F~2Fusdagcc.sharepoint.com~2Fsites~2Ffs-nfs-oft&fileId=AC6563D5-20F0-46EF-932C-8DEB3411AD38&ctx=files&viewerAction=view

Thanks @ASprinkle - adding the PDF here as well
[Chrismas_trees_Service_Blueprint_v02-06192019.pdf](https://github.com/18F/fs-open-forest-platform/files/3307353/Chrismas_trees_Service_Blueprint_v02-06192019.pdf)
