### ISSUE TITLE
As a UX designer I want to develop a set of questions to ask SME so that I can make informed decisions when developing the service design blue print.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#623]
## Notes
* What are things we should consider when making this story *

This story is Part 1 of Epic #616 

## Acceptance Criteria
- [x] We have a list of SME contacts.
- [x] We have a draft blue print that is ready for SME validation.
- [x] We understand what the questions are that we want to ask SME.
- [x] The interview questions are in a document that team members can find.

## Tasks
- [x] Work with PO and/or Aaron to build on the draft blue print, continue iterations.
- [x] Identify SMEs who could review the blue print and confirm it's accuracy.
- [x] Get SME contact information.
- [x] Develop research questions.
- [x] Begin contacting SMEs to schedule interviews.
- [x] PO approved.

## Definition of Done
- [] Pull requests meet technical defintion of done
- [] Compare finished design with mockup
- [] Usability tested

**Comment by ASprinkle** [comment]
With guidance from Lisa and Amber (at a minimum) the following Pilot fores SMEs should review the service design blue print:
Tammy Williams (ARP)
Paul Rau (Shoshone)

We want to them to review the blue print and provide their input; identifying any inconsistencies or gaps in the current Open Forest Christmas tree process.

[Christmas trees Pilot Forest Contacts List.xlsx](https://github.com/18F/fs-open-forest-platform/files/3167837/Christmas.trees.Pilot.Forest.Contacts.List.xlsx)

**Comment by lisaredux** [comment]
> @lisaredux Is this enough of a "question" for SME when they review the blueprint?: We want to them to review the blue print and provide their input; identifying any inconsistencies or gaps in the current Open Forest Christmas tree process.
> 

@ASprinkle — yes, I think so. Validating the user steps and Forest Service side processes seems to be the end goal here. I'll work on getting a shareable format attached here.

**Comment by ASprinkle** [comment]
@lisaredux RE "begin contacting SME"  I can help doing that once there's a shareable format.

**Comment by lisaredux** [comment]
@ASprinkle Attaching a cleaned up version to show SMEs. Let me know if you need anything updated. I can make changes in the PDF with AcrobatPro [Chrismas_trees_Service_Blueprint_v01-05132019.pdf](https://github.com/18F/fs-open-forest-platform/files/3174357/Chrismas_trees_Service_Blueprint_v01-05132019.pdf)

**Comment by ASprinkle** [comment]
@lisaredux thank you - can we also save that PDF in a location in the Drive?  I'll be inviting you to the SME review's that I schedule with Paul and Tammy.
