### ISSUE TITLE
As a UX designer I need to validate the initial service blue print with SME to determine if more refinement is needed so that i understand the permit flow.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#624]
## Notes
* What are things we should consider when making this story *

This story is part 2 of Epic #616 

## Acceptance Criteria
- [x] The draft blue print has been reviewed
- [x] Refinements have been documented and will be applied to the blue print

## Tasks
- [x] Schedule Interviews
- [x] Conduct Interviews
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by jdamis4XD** [comment]
@ASprinkle This is in progress already, correct? Adding  @lisaredux @DawnDesigner for visibility.

**Comment by ASprinkle** [comment]
Yes it is.  I have scheduled interview times with two stakeholders to review the blueprint
Shoshone, Paul Rau is scheduled for 5/21
Araphaho-Roosevelt, Tammy Williams and Laura Schaffer are scheduled for 5/31

**Comment by ASprinkle** [comment]
@jdamis4XD is compiling the notes from today's review from the ARP.

**Comment by jdamis4XD** [comment]
Meeting notes from 5/31 meeting with Arapaho and Roosevelt staff:
https://docs.google.com/document/d/1b2rHW_SM7a8GK-FBlcN97O8QNwZCuMFC7niDGhmiXlA/edit?usp=sharing
