### ISSUE TITLE
As an Open Forest team member I want to have an understanding of what a public facing feedback system for Open Forest might look like.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#626]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] We have participated in a Demonstration of what has been developed for other systems
- [x] We have an understanding of what we will need to do
- [x] We have captured notes on future needs, and begun to develop new issues associated with story

## Tasks
- [x] Complete participation in demo
- [x] Notes are compiled and saved in a location accessible by team members
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [x] Usability tested (NA)

**Comment by ASprinkle** [comment]
A demonstration is being scheduled for 0900-1000 PST on Friday 5/10

**Comment by jdamis4XD** [comment]
@ASprinkle 

Meeting notes:
Tool name: Touchpoint

Schedule: 
- Going into beta with 20 HISP for the next 4 weeks 
- ATO will take another 4 weeks
- Expect by midsummer to be able to work with agencies interested in the tool

Features:
- 3 layout formats of how to apply the tool
- Utilizes Google tag manager, just requires to embed the code on the site
- The CSS for the questionnaire can utilize parent style sheets to be on agency brand
- Reporting capability limited to just a simple table read out at the moment, but team looking to iterate
- User management is supported
- Targeting capability is provided to support pages, site wide, or url
- Questionnaire will be editable
- Admin users require an email address that ends in ".gov", but team will be iterating to support other email address types (for contractors)

OF concerns:
- More robust reporting potentially
- Security team sign off could be a blocker (Lauren mentioned that USDA will have an agency participating as a HISP in the beta, so that might be resolved)

Touchpoint demo recording: https://drive.google.com/open?id=13Nw0pLMTECOUZwxxVP5jWLFNsm_cjESd

**Comment by ASprinkle** [comment]
https://trello.com/c/yVRyvSdk
A Trello board story as been created and addresses the following:

-Decision around whether or not to join Touchpoint beta testing in July
-Determine whether or not the questions associated with Touchpoint meet the needs of the Customer Experience Strategy Team
-Determine security compliance actions that would need to be taken to have Open Forest become part of the beta test in July in preparation for the 2019/2020 Christmas tree season.
