### ISSUE TITLE
As an applicant I would like to be able to understand the purpose of both of the permit types before I make a decision to apply for one or the other so that I do not spend too much time clicking back and forth.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#627]
## Notes
* What are things we should consider when making this story *
This story was created to break up #565 from the description of different types of permit and the additional information that would reduce the number of clicks for the applicant.

## Acceptance Criteria
- [x] The landing page includes more information about each permit in a format that is easy to read on web and mobile.
- [x] The landing page includes a "Still Not Sure" or "help me find a permit" link that works.

## Tasks
- [x] Include 'learn more' link on both boxes and an 'apply' button
- [x] Organize the content of the information on the landing page; user flow in a way that is easy to understand.
- [x] Build a wireframe of the workflow.
- [x] Wire frame drafted, reviewed and PO approved
- [x] Build for site
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by jdamis4XD** [comment]
@DawnDesigner You mentioned that there was user research in our earlier refinement meeting today. 
 Could you direct us to where we can locate that information to determine what additional copy is needed.  Thanks. Adding @ASprinkle @lisaredux for awareness.

**Comment by lisaredux** [comment]
@ASprinkle we (@jdamis4XD @DawnDesigner and I) are collectively working on this, but we will need to schedule a meeting with you to vet the new content organization. I am currently working on wireframing the content for this and #530 and #531 .

**Comment by ASprinkle** [comment]
@lisaredux @DawnDesigner @jdamis4XD The earliest I could find with our calendars is 5/22... I have 130 PST open this Friday 5/17 - is that to late for east coast?

**Comment by lisaredux** [comment]
@ASprinkle Here's the wireframe of the content for your review https://sketch.cloud/s/MGMV9

**Comment by ASprinkle** [comment]
Regarding the ?? on the landing page wire frame. we have yet to confirm the best terms (non-FS heavy) to describe these. Perhaps we'll learn more through usability testing. For now, let's call them "Non-Commercial Group Use Permit", and "Temporary Outfitting and Guiding Permit"

"Instead of short-term permit for outfitting and guiding" lets try "An outfitting and guiding permit that is valid for no more a 180-day period" or something to that effect? OR we can see what usability testing gives us.

**Comment by DawnDesigner** [comment]
A/B testing with two prototypes in progress for these issues and will be removed from blocked when testing is completed and these issues are refined and put into ready.
#530 , #531, #565 and #627

**Comment by DawnDesigner** [comment]
@ASprinkle  @lisaredux 

This testing study is now complete. Findings and recommendations can be found on this repositories Wiki (Design and Research) here:

https://github.com/18F/fs-open-forest-platform/wiki/Usability-Testing:-Special-Uses-(Content-Flow-Study)-June-2019

Since this story relates specifically to the actual copy on the landing page, it is connected to US #565 - the layout and images - both of those tasks can now be in progress. Can this story be moved to "In Progress"?

**Comment by ASprinkle** [comment]
@DawnDesigner @lisaredux do we have a mock of this landing page to prepare it for dev?

**Comment by DawnDesigner** [comment]
@ASprinkle @lisaredux  Working on mockup up now.  Lisa and I will need to draft the actual text to be sure all requirements are covered before I add it to the mockup.  Should be able to do that today.

**Comment by DawnDesigner** [comment]
Proposed text for landing page boxes based on user testing: @ASprinkle and @lisaredux  Please review and give input:

Non-Commercial Permit

A free permit for activities of 75 or more people 
No entry fees can be charged 
Primary purpose isn’t selling goods or services.
Application time: Appx 35 minutes to 1 hour
You will need: Event details such as date, time etc.

button: Learn More
button: Apply



Temporary Outfitter’s Permit

Charging an entry fee
For outfitters and guides
Short-term, non renewable
Application time: Appx 1 to 3 hours
You will need:  Certificate of good standing or equivalent, an operating plan, liability insurance, guide id, and more (see “Learn More” for details)	

button: Learn More
button: Apply

**Comment by ASprinkle** [comment]
[Story627_mock text post testing.docx](https://github.com/18F/fs-open-forest-platform/files/3311489/Story627_mock.text.post.testing.docx)
Hi @DawnDesigner @lisaredux I have my edits in this attached word doc with comments. Thanks!

**Comment by DawnDesigner** [comment]
@ASprinkle @lisaredux  - With the changes in the boxes,  there is also a need to edit both the title of the page (in response to the comments in the user testing) and the opening paragraph.

__________________________________________________________________________________________________________

CURRENT PAGE TITLE AND OPENING PARAGRAPH


**Apply for a permit with Open Forest**

If you know which permit you need, click on the permit type below to submit an application using a login.gov account. If you are unsure of which you need, click on “Help me find a permit,” and we’ll provide you with additional guidance.

_________________________________________________________________________________________________________

Suggested changes: Remove Open Forest from the title until we can add text about OF to give users context, and the opening paragraph does not mention the learn more button.

__________________________________________________________________________________________________________

PROPOSED TITLE AND OPENING PARAGRAPH


**Apply for a Permit with the National Forest Service**

If you know which permit you need, click ‘apply’ to submit an application using a login.gov account. If you are unsure, either use our wizard (scroll down), or click the learn more button for a specific permit type below for additional guidance in choosing a permit for your event.

**Comment by lisaredux** [comment]
@ASprinkle @DawnDesigner Thanks for the update. 
My only concern with the changes on the word doc is the passive voice for non-comm and the other for Temporary Use, for example:
![image](https://user-images.githubusercontent.com/26801590/59871457-a1615000-9365-11e9-918f-3995ddd4fd82.png)
![image](https://user-images.githubusercontent.com/26801590/59871590-ee452680-9365-11e9-9218-260555bd2358.png)

As far as Dawn's recommended updates, looks good. Should we include "special use" in the title somewhere so it would read "Apply for a special use permit...." or something like that?


> PROPOSED TITLE AND OPENING PARAGRAPH
> 
> **Apply for a Permit with the National Forest Service**
> 
> If you know which permit you need, click ‘apply’ to submit an application using a login.gov account. If you are unsure, either use our wizard (scroll down), or click the learn more button for a specific permit type below for additional guidance in choosing a permit for your event.

**Comment by DawnDesigner** [comment]
@ASprinkle  @lisaredux  Good idea: ' Apply for a Special Use Permit' as the title. Would that be right?

Here is modified Temp Outfitters side:

- An entry fee is charged
- For outfitters and guides
- Short-term, non renewable
- Application time: Appx 1 to 3 hours
- You may need:  Certificate of good standing or equivalent, operating plan, liability insurance, and more (see “Learn More”)

**Comment by ASprinkle** [comment]
"Apply for a Special Use Permit" - do not refer to the "National Forest Service"
I am good with any changes from passive voice - I will need help with that on occasion

**Comment by lisaredux** [comment]
@ASprinkle @DawnDesigner Great, thanks. I have a question and further suggested changes. Hope I'm not overcomplicating:

First the question: at what point in our updates did we change the timing from 45-65 min (story 530) to 1-3 hours? Just wondering.

And my suggestions:

- For outfitters and guides who charge a fee [update here]
- Short-term, non renewable
- Application time: approx. 1 to 3 hours [update here]
- You may need: Certificate of good standing or equivalent, operating plan, liability insurance, and more (see “Learn More”)

**Comment by ASprinkle** [comment]
@lisaredux I am not aware of changing the time estimate. I assumed we were operating with the same information as originally researched; preference to use original research findings for time estimate (Story 530).

I am ok with the update suggestions.

Lets move forward with the mock, and refine from there.  

Thanks @lisaredux @DawnDesigner

**Comment by DawnDesigner** [comment]
@ASprinkle @lisaredux - No problem, I'll make the change to the mock up as final, and then you can refine it from there if needed.

btw - bullets are not considered sentences and so don't need to be grammatically correct.  They are just listing separate items for a quick read.

Here is the final with all suggestions.  Thanks!

Non-Commercial Permit

A free permit  for activities of 75 or more people
No entry fees can be charged
Primary purpose isn’t selling goods or services.
Application time: Appx 35 minutes to 1 hour
You will need: Event details such as date, time etc.

button: Learn More
button: Apply

Temporary Outfitter’s Permit

For outfitters and guides who charge a fee
Short-term, non renewable
Application time: approx 1 to 3 hours
You will need: Certificate of good standing or equivalent, an operating plan, liability insurance, guide id, and more (see “Learn More” for details)

button: Learn More
button: Apply

**Comment by DawnDesigner** [comment]
@ASprinkle @lisaredux  - Amber, Lisa is asking if this text is approved.  It's exactly as I mocked up on issue #565 - but I believe you suggested we might refine the text further. How should we proceed?

One of the 'drop-dead' requirements is that you, or a designee, must be 18 to sign the agreement.  While I added that into the user testing site A - it wasn't determined by the group if that should be in this list or not.  I'm guessing there was research by 18F earlier that may have addressed this already and there was a reason it was left off.

Attaching mock ups from user story #565 for reference.

![SU - Landing Page 3](https://user-images.githubusercontent.com/47989077/60101412-b8b78900-9729-11e9-9902-f7cbd1ab6af4.png)

**Comment by lisaredux** [comment]
@ASprinkle thanks for clarifying — here's the related, latest mockup. 
Did you need anything else from design — either @DawnDesigner or me? 

![59945877-eacda000-9436-11e9-9afe-cb420bdfced0](https://user-images.githubusercontent.com/26801590/60186644-364aca00-97fa-11e9-94c2-0a1af6198641.png)

**Comment by ASprinkle** [comment]
@DawnDesigner @lisaredux 

The design looks great. Please make the following text changes:
Non-commercial permit - Change to:  "Non-commercial Group Use Permit"
Temporary Outfitter's Permit - Change to: "Temporary Outfitter and Guide Permit"
Application Time: Appx. 35 minutes to 1 hour - Change to: "Application Time: Appx. 20-30 minutes"
Application Time: Appx.  1 to 3 hours - Change to" Application Time: Appx. 1 hour"

Please make the following text changes. I referenced back to 530, and would like to see 20-30 mins for Non-com and 1 hour for Temp OG.  This is close to what was researched. 

Once we make those small changes, let's move it to the next step. Thanks!

**Comment by ASprinkle** [comment]
The next step being, that it goes back into "Ready" or "In Progress" for the dev team to pick up and complete.

**Comment by lisaredux** [comment]
@ASprinkle Here's the updates. Including a linked PDF so development can copy-paste text. 

[SpecialUse-LandingPage07032019.pdf](https://github.com/18F/fs-open-forest-platform/files/3356661/SpecialUse-LandingPage07032019.pdf)
![SpecialUse-LandingPage07032019](https://user-images.githubusercontent.com/26801590/60621644-30ca2280-9dac-11e9-819b-d6b28ce62120.png)

Ready for DEV. Let us know if you have questions @mtlaney

**Comment by ASprinkle** [comment]
Looks great! thank you.  Ready for Dev!

**Comment by DawnDesigner** [comment]
@lisaredux @ASprinkle  Please note that this mockup does not show the two images correctly.  The teens on the rock should be on the left (not the one with Smokey). It's noted here in the user story, but I'd update the mock up for record and so the developer uses the right image.  Thanks

**Comment by ASprinkle** [comment]
Looks great @mtlaney!
