### ISSUE TITLE
As a Christmas tree permit recipient, I want to see rules and guidelines without code artifacts so that I can easily understand the directions.

### ISSUE THREAD

**Issue by lisaredux** [18F/fs-open-forest-platform#632]
## Notes
Currently the christmas tree permit holder receives three attachments in the email that is sent to them after they purchased their permit.
There are two attachments that house the permit rules. One attachment arrives in .html format, and the other arrives in .txt format.
In either case, there are code artifacts that are present in the attachments for key pieces of information that the permit holder would need to know in order to be in compliance with the rules on that forest.

[permit-rules.txt](https://github.com/18F/fs-open-forest-platform/files/3157920/permit-rules.txt)

## Acceptance Criteria
- [x] The permit rules attachment(s) in the email do not have code artifacts in them
- [x]  The permit rules attachment(s) in the email correctly displays the same rules and information that was "agreed to/understood" on the Open Forest website as part of the purchase process.
- [x] When an update is made to a rule or guideline, it is also reflected correctly in a permit rules email attachment.
- [x] I do not see code artifacts on the Open Forest site.

## Tasks
- [x] Replace markdown package
- [x] Refactor the code
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

<img width="639" alt="Screenshot 2019-05-08 10 57 18" src="https://user-images.githubusercontent.com/26801590/57385231-0ed36b80-7180-11e9-8187-97b2a96dd021.png">

**Comment by lisaredux** [comment]
@ASprinkle - added this issue along with #629 , #630 , #631 for everything related to emails and downloading the permit and rules & guidelines in Christmas trees

**Comment by ASprinkle** [comment]
Thanks @lisaredux 

I closed 629 and 630 and indicated rationale in those respective stories.

**Comment by ASprinkle** [comment]
from stand up: updated markdown package. trying to figure out why svg to html conversions are occurring.

**Comment by briandavidson** [comment]
I need to test this on our staging environment at this point so we can simulate a permit purchase, which generates the email that gets sent out.

**Comment by ASprinkle** [comment]
I tested it just now for the Mt. Hood and when I view the documents in the print window from Open Forest, I can see code artifacts for Tree Height and Stump Height
![image](https://user-images.githubusercontent.com/33435621/60611440-26dbfb80-9d7b-11e9-8cbd-43a90030468a.png)

I can also see the code artifacts in the attachments in the email.

**Comment by briandavidson** [comment]
@ASprinkle yah that makes sense -- I should have been more clear: the updated code has not been deployed to our staging environment yet. I'll let you know once it's been deployed and ready to check out.

**Comment by briandavidson** [comment]
While working on this I came across a larger issue. The email attachments use a [template file](https://github.com/18F/fs-open-forest-platform/blob/dev/frontend/src/assets/content/arp/tree-cutting-rules.md) with generic placeholders like `{{stumpDiameter}}` and `{{cuttingAreas}}`.

Currently we have to rely on [some code](https://github.com/18F/fs-open-forest-platform/blob/03a518c277eb5f448d1c4dbb3eeb8032424f9c87/server/src/services/christmas-trees-permit-svg-util.es6#L237) that is specific to certain forests. This is problematic because we want code that is future proof -- that can handle the specific data for any new forest we add just fine.

We can solve this by changing the the way we name some of our placeholders in our template files to be more generic. Specifically, the ones dealing with cutting areas, i.e. `{{sulphurDate}}`, `{{elkCreekDate}}`, `{{redFeatherLakesDate}}`. 

The image below captures the gist of what I'm suggesting we need to change:
![image](https://user-images.githubusercontent.com/5187168/61004110-3cc95d80-a333-11e9-81f3-ede9cb8a4846.png)

@ASprinkle does this make sense? Please advise.

**Comment by ASprinkle** [comment]
@briandavidson I think it makes sense.
Goal - Printed rules and guidelines that are emailed do not have code in them.
We always want the ability to easily add or change information specific to a forest, whether it is new this season, or one of the original four pilot forests.

Does this seem like a larger issue than what was initially thought? Do you envision additional stories, or epic potential?

**Comment by briandavidson** [comment]
@ASprinkle this is definitely a larger issue than initially thought but no additional stories or anything are necessary. I've completed the work required to facilitate this, the **key thing** here is making sure that in the future whoever is responsible for creating the template file for a new forest follows this naming convention where the cutting areas are all in uppercase.

There could be one follow up task for this potentially: if we have existing documentation on the process for adding a new forest (specifically in regards to how to create the template file), we should definitely update it to reflect this new convention. I'll take a look and see what we have.

**Comment by briandavidson** [comment]
@ASprinkle we're all set! I moved the issue over to awaiting acceptance, and on our staging environment is ready whenever you want to check it out.

**Comment by ASprinkle** [comment]
Success! no code artifacts in the info receveid via email, nor in the info you can print from Open Forest. 

However, I did see code artifacts here in the Christmas tree cutting rules section:
![image](https://user-images.githubusercontent.com/33435621/61161360-52b45b00-a4b8-11e9-8d51-452c8317779e.png)

**Comment by briandavidson** [comment]
@ASprinkle that should be taken care of now too, thanks for pointing it out!

**Comment by ASprinkle** [comment]
Yes, it looks great on staging. No code artifacts in the "Christmas tree cutting rules" section!
