### ISSUE TITLE
As an Open Forest Admin, I would like to be able to access the staging and production sites (depending on my roles) so that I can accomplish my administrator tasks.

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#643]
I see this in PRODUCTION for both SU and XMAS trees admin. I am unable to produce locally.

![Screen Shot 2019-05-10 at 10.46.21 AM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/de95a90f-b46d-47c2-ae2a-10d5954a305a)

## Notes
Currently, Open Forest Christmas tree production administrators cannot access the admin side through eAuth. They are routed through login.gov. Once back in the Christmas tree page, there are no Christmas tree admin functions available. For the production side, this is a high priority. We want to make sure Christmas trees is functional so that we (Open Forest team and FS Admins) can continue to access its information easily and demonstrate it's use.

Currently, the MBS staging admin site is not accessible through eAuth
## Acceptance Criteria
- [x] Open Forest administrators can access the admin sites they have roles for.

## Tasks
- [x] Check eAuth staging certificates
- [x] other - needs dev refinement- 
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
#613 has corrected this bug on my end for staging, will need another to verify on staging as well.

@ASprinkle The work @davemcorwin has done on #613 seems to have corrected this bug atleast on my end, can you verify? (Fix is live on staging but not on PROD yet).

**Comment by ASprinkle** [comment]
@mtlaney Success in Staging!!! 

Here is the screen shot flow that I encountered when logging into Christmas Tree admin staging; It all looked correct to me.  I was also able to access Special Uses admin staging as well!

![image](https://user-images.githubusercontent.com/33435621/57784421-65f8b380-771f-11e9-8a45-ff3f60accf31.png)

![image](https://user-images.githubusercontent.com/33435621/57784430-6b55fe00-771f-11e9-93a2-964e62572bda.png)

![image](https://user-images.githubusercontent.com/33435621/57784444-70b34880-771f-11e9-8de1-81c3d20f3a44.png)

![image](https://user-images.githubusercontent.com/33435621/57784455-7577fc80-771f-11e9-9965-b089377e8b81.png)

![image](https://user-images.githubusercontent.com/33435621/57784476-79a41a00-771f-11e9-9a44-30192b04b49a.png)
