### ISSUE TITLE
As an Open Forest Admin, I would like to be able to access the staging and production sites (depending on my roles) so that I can accomplish my administrator tasks.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#645]
## Notes
Currently, Open Forest Christmas tree production administrators cannot access the admin side through eAuth.  They are routed through login.gov.  Once back in the Christmas tree page, there are no Christmas tree admin functions available.  For the production side, this is a high priority. We want to make sure Christmas trees is functional so that we (Open Forest team and FS Admins) can continue to access its information easily and demonstrate it's use.

Currently, the MBS staging admin site is not accessible through eAuth

## Acceptance Criteria
- [ ] Open Forest administrators can access the admin sites they have roles for.

## Tasks
- [ ] Check eAuth staging certificates
- [ ] other - needs dev refinement- 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical defintion of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
There are other stories in Ready for Master, that may resolve this issue... ?

**Comment by ASprinkle** [comment]
closing - redundant with #643
