### ISSUE TITLE
SNYK 5-13-2019

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#648]
## Notes
```
Testing /home/circleci/project/frontend...

✗ Medium severity vulnerability found in core-js
  Description: Cross-site Scripting (XSS)
  Info: https://snyk.io/vuln/SNYK-JS-COREJS-174627
  Introduced through: core-js@2.6.1
  From: core-js@2.6.1
```

## Acceptance Criteria
- [x] Snyk Passes

## Tasks
- [x] Update Snyk Policy File
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical defintion of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by davemcorwin** [comment]
@ASprinkle Snyks is passing.
