### ISSUE TITLE
As a Christmas tree FS administrator running a report of permit sales, I would like the report generated title to be shorter, and I would like to see my Forest name capitalized and not shortened so that it is easier to read.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#651]
## Notes
* What are things we should consider when making this story *

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/8ec05c18-cfe4-4d3a-bf52-33c59ea34a3c)

![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/27eb0f71-0171-40dc-ae5f-3f1f461ea7e8)

## Acceptance Criteria
- [x] The Report Generated title is easy to read, and does not include HH:MM:SS information
- [x] The forest names in the table are written with the first letter capitalized. (Mt. Hood, Flathead, Shoshone, Arapaho-Roosevelt)
- [x] Arapaho-Roosevelt is not shortened to "arp"

## Tasks
- [x] Change time output to more readable format
- [x] Use the forest long name as opposed to the short name
- [x] Determine how to use very long names in the table
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [x] Compare finished design with mockup
- [x] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle @DawnDesigner  Updated the display for examples. Please confirm that this is ready to assign to DEV.

<img width="723" alt="Story651" src="https://user-images.githubusercontent.com/26801590/60183039-7d818c80-97f3-11e9-9c50-6fd09f4f4a55.PNG">
<img width="551" alt="Story651-2" src="https://user-images.githubusercontent.com/26801590/60183048-7fe3e680-97f3-11e9-97ac-53c6939a8466.PNG">

**Comment by ASprinkle** [comment]
Thank you for the heads up on ready for review. 

In the report's title for "All" can it read "All Forests"?

Looks great!
