### ISSUE TITLE
As an admin I would like to access the christmas trees admin areas of the application at /admin/christmas-trees

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#653]
## Notes
Attempting to navigate to `/admin/christmas-trees` redirects immediately to `/access-denied`. Special Use authentication is working properly (`/admin/applications`).

Verified on `production`, `staging`, and `dev`.

This is because this is wrong url! Adding a redirect for future admins who don't know the correct urls. See comment for more info.

## Acceptance Criteria
- [x] An admin should be able to access the christmas trees admin area by navigating to `/admin/christmas-trees`
- [x] An administrator is automatically directed to the generate reports page as the default admin page.

## Tasks
- [x] Add redirect
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- [ ] Usability tested

**Comment by davemcorwin** [comment]
This is a bit of a false alarm. The actual christmas tree admin urls are:
/admin/christmas-trees/reports
/admin/christmas-trees/season-dates
/admin/christmas-trees/district-dates

However, I think it makes sense to add a redirect here just in case, updating the issue accordingly.

**Comment by ASprinkle** [comment]
@davemcorwin I was able to successfully access the admin staging site for christmas trees this morning using https://open-forest-staging.app.cloud.gov/admin/christmas-trees/reports

![image](https://user-images.githubusercontent.com/33435621/58027327-3a821a00-7acd-11e9-901f-e00d048bd0c1.png)

**Comment by mtlaney** [comment]
@ASprinkle The reason /admin/christmas-trees isn't working is that it isn't loading a component. For instance /admin/applications loads the Permit Applications component after it authenticates. Is there a certain default page we would like to see for /admin/christmas-trees? I would think the christmas tree report page but it's up to you.

Our current 4 options are:
- [ ] christmas tree report page
- [ ] change season dates
- [ ] change cutting area dates
- [ ] create a new admin page for christmas trees 

 Let me know what you think and we can knock this one out.

**Comment by davemcorwin** [comment]
Moving to Backlog, it is not essential to be done immediately, can be moved to ready once we agree on the desired behavior.

**Comment by ASprinkle** [comment]
@mtlaney updated for landing on the generate reports page

**Comment by ASprinkle** [comment]
When navigating to https://open-forest-staging.app.cloud.gov/admin/christmas-trees
This is what I initially encountered:  I was able to click on the tabs and get to where I wanted to go.
When I tried again, after clearing my cache, I was unable to get back here.
![image](https://user-images.githubusercontent.com/33435621/58269643-debdc800-7d3c-11e9-9477-d95b137f2e73.png)

So I tried incognito window to see if it would direct me to the Generate reports page.

![image](https://user-images.githubusercontent.com/33435621/58269664-e7160300-7d3c-11e9-82dd-92f241b046f0.png)
![image](https://user-images.githubusercontent.com/33435621/58269672-eb422080-7d3c-11e9-84f3-4f4ef360f3ae.png)

When attempting to log in using incognito window to admin/Christmas-trees/reports url this is what I encountered:
![image](https://user-images.githubusercontent.com/33435621/58269686-f301c500-7d3c-11e9-8720-fc4d073550a4.png)
![image](https://user-images.githubusercontent.com/33435621/58269698-f6954c00-7d3c-11e9-9c62-7a9e103a29d4.png)

I cleared my cache and tried https://open-forest-staging.app.cloud.gov/admin/christmas-trees/reports again in a regular window
![image](https://user-images.githubusercontent.com/33435621/58269709-fc8b2d00-7d3c-11e9-9eee-196f8504524a.png)
![image](https://user-images.githubusercontent.com/33435621/58269715-ff861d80-7d3c-11e9-8b57-74c444ada2db.png)
![image](https://user-images.githubusercontent.com/33435621/58269723-0319a480-7d3d-11e9-8ede-5b86cab73659.png)
![image](https://user-images.githubusercontent.com/33435621/58269738-07de5880-7d3d-11e9-8449-1966fa1124c7.png)

So then I cleared my cache again and tried the new URL /admin/christmas-trees
![image](https://user-images.githubusercontent.com/33435621/58269756-1167c080-7d3d-11e9-9c0b-30db5b5d27a1.png)
![image](https://user-images.githubusercontent.com/33435621/58269778-1593de00-7d3d-11e9-87f5-6cd2d4437b5a.png)
![image](https://user-images.githubusercontent.com/33435621/58269787-19276500-7d3d-11e9-8694-10798bf9d29e.png)

I was also recently issued a NEW PIV card. Perhaps I am having a certificate error in eAuth. I have encountered this when I attempt to sign in to eAuth in Google Chrome, but not in IE.  Not sure if that's part of my issue here....

**Comment by ASprinkle** [comment]
As of this morning, I am still not able to log in to Admin staging for the christmas tree side using
https://open-forest-staging.app.cloud.gov/admin/christmas-trees/reports and/or
https://open-forest-staging.app.cloud.gov/admin/christmas-trees/

**Comment by davemcorwin** [comment]
Sent an email to EAuth help desk

**Comment by ASprinkle** [comment]
excellent. This story is blocked until we can access staging through eAuth.

**Comment by davemcorwin** [comment]
Remedy Ticket #INC000003502940
icam.services@ocio.usda.gov

**Comment by ASprinkle** [comment]
SUCCESS!!!!!!
