### ISSUE TITLE
As a user, I want to authenticate with Login.gov to access special use permits

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#654]
## Notes
When attempting to authenticate with Login.gov to access the Special Uses area of the application, I receive the following error:

![Screen Shot 2019-05-17 at 2.31.30 PM.png](https://images.zenhubusercontent.com/55539b1a4f7a08fbb7f2c453/ff33dac0-50ba-4f3e-be62-e4bded50e806)

Verified on `production` only, this is a configuration issue for the `production` environment.

## Acceptance Criteria
- [x] A user can authenticate with Login.gov and access Special Uses

## Tasks
- [x] Update `redirect_uri` configuration
- [x] Verified on staging
- [x] PO approved

## Definition of Done
- [x] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- [] Usability tested

**Comment by ASprinkle** [comment]
I was able to authenticate through Login.gov and be successfully redirected to Open Forest to continue the application process. 

Screen shots of successful steps:
![image](https://user-images.githubusercontent.com/33435621/58026699-e591d400-7acb-11e9-9cce-909b497c2638.png)

![image](https://user-images.githubusercontent.com/33435621/58026708-ec204b80-7acb-11e9-85ab-f439a6b295ec.png)

![image](https://user-images.githubusercontent.com/33435621/58026720-f0e4ff80-7acb-11e9-9ac7-a97e6e0f0b56.png)

![image](https://user-images.githubusercontent.com/33435621/58026727-f5a9b380-7acb-11e9-955d-c3eebabbbc23.png)

![image](https://user-images.githubusercontent.com/33435621/58026737-fa6e6780-7acb-11e9-8d1f-c8ef0dce180a.png)

![image](https://user-images.githubusercontent.com/33435621/58026749-ffcbb200-7acb-11e9-9234-0a26b6881b54.png)
