### ISSUE TITLE
Usability research for Special Use stories #627, 530, 531

### ISSUE THREAD

**Issue by lisaredux** [18F/fs-open-forest-platform#656]
## Notes
* What are things we should consider when making this story *

This story is for the purposes of capturing the work related to the usability research around the content flow for a special uses permit applicant.

## Acceptance Criteria
- [x] We have an understanding of what will work for a content strategy for these stories..
- [x] We know what changes (if any) we should make to the designs for the workflow and content of 627, 530 and 531

## Tasks
- [x] Recruit participants
- [x] Create research plan
- [x] Create usability script 
- [x] Have the usability tests
- [x] Synthesis
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by lisaredux** [comment]
@ASprinkle @jdamis4XD @DawnDesigner new story for the discussed research. Reword as needed.

**Comment by lisaredux** [comment]
Working on the research plan today

**Comment by lisaredux** [comment]
@ASprinkle - Here is the research plan that @jdamis4XD + @DawnDesigner + I came up with: https://docs.google.com/document/d/1xLVYnB-HESkDD7muVoDEUjhHwqj3eieC3do7AU3Rpzk/edit?usp=sharing

Please review at your convenience, and let us know if & when you'd like to have a quick meeting about this and recruitment.

**Comment by ASprinkle** [comment]
@lisaredux I reviewed it.
I have a few minor edits. And the following comments given my limited experience with developing research plans:
Research questions - should those be phrased as if asking a participant? So, instead of "Do participants understand..." should it be "Do you understand which permit you need before selecting one of the call-to-action buttons from the home page?"
I would add: After the application submitted, "Do you have an understanding of what the next step is" or something like that.
For methods - should we describe how the remote usability session will take place and whether or not it will be recorded?  Also, if there are observers, are they taking notes? Where will notes and possible recordings be stored?
Participants and recruiting - I would like to see some handful of FS special uses administrators (at least one from the MBS, and some from other forests) . I understand that may be hard to do with short notice.

**Comment by lisaredux** [comment]
@ASprinkle thanks for the comments. Helpful. Let's talk about recruiting today and when we might want to include SUA's into the usability studies. 

For the way the questions are phrased, the test script will ask the questions in a more direct form like "Do you understand which permit you need....". The test script also includes methods and who is taking notes. We can discuss today as well. Thanks!

**Comment by lisaredux** [comment]
@ASprinkle so far, we have 6 participants scheduled for the sessions June 11-13. All of them are from the OG Contact list. We're wondering if you gathered any leads for non-commercial group participants.

**Comment by lisaredux** [comment]
July 11- two participants showed, one no-show (complete)
------
June 12- three participants scheduled
June 13- one participant scheduled

**Comment by lisaredux** [comment]
**Timeline**
Study design: May 28th - 31th
Amber meets with Sue - SUA: June 4
Recruiting: May 31th - June 6
Data collection (for example, interviews): June 11 - 13 (testing)
Top-line synthesis: June 13 (distro to product team)
Collaborative analysis: June 14
Collaborative synthesis: June 17
Outcomes: June 18th (Zenhub updates)

**Comment by lisaredux** [comment]
Updated timeline for completion—
Collaborative synthesis: June 18
Outcomes: June 19

**Comment by DawnDesigner** [comment]
This testing study is now complete. Findings and recommendations can be found on this repositories Wiki (Design and Research) here:

https://github.com/18F/fs-open-forest-platform/wiki/Usability-Testing:-Special-Uses-(Content-Flow-Study)-June-2019

**Comment by ASprinkle** [comment]
I realized this was not part of the A/C so I am editing the formatting of the information. When I viewed the page initally, it looked like this:
![image](https://user-images.githubusercontent.com/33435621/59791640-6e488f00-9287-11e9-860b-657f98867031.png)
![image](https://user-images.githubusercontent.com/33435621/59791648-71437f80-9287-11e9-8b3a-864003786247.png)

This format is hard to read, so I am editing it so that it follows the formatting and style of other pages in the wiki:
![image](https://user-images.githubusercontent.com/33435621/59791680-83252280-9287-11e9-969f-10c8d7eee491.png)
![image](https://user-images.githubusercontent.com/33435621/59791690-86b8a980-9287-11e9-9ef5-f07eee070059.png)

**Comment by ASprinkle** [comment]
Scenario One:
https://docs.google.com/document/d/1R3cpImBPuvYrhReNGc4Vp5UKjKODP6w-QlOhifZbQb0/edit?usp=sharing

Scenario Two: https://docs.google.com/document/d/1US5mIDVxmOvQqc7G4UizJGAj5sSL1Wj5CgqqQRcSM40/edit?usp=sharing

**Comment by DawnDesigner** [comment]
@ASprinkle @lisaredux @aaronburk   -  I believe this is ready to close - research is finished, changes are done, mock ups approved and moved into dev. Can you advise?
