### ISSUE TITLE
As a user I want to be able to authenticate with EAuth and no interruptions

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#663]
## Notes
As part of debugging EAuth connectivity issues, the EAuth team changed a piece of the configuration. However, this was not standard and it something that Open Forest can control so we will alter our configuration allow EAuth to revert the configuration to standard.

Add SAML configuration parameter to ignore Requested Authn Context.

## Acceptance Criteria
- [x] No interruptions in availability of EAuth authentication

## Tasks
- [x] Add additional environment variable to specify configuration value
- [x] Add configuration value to SAML configuration
- [x] Update environment variables in dev, staging and prod
- [x] PO approved
- [x] Eauth update configuration in `staging`
- [ ] Eauth update configuration in `production`

## Definition of Done
- [x] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- ~[] Usability tested~

**Comment by ASprinkle** [comment]
@davemcorwin can you check the task boxes or minimize them if they no longer apply. Thanks! :)
