### ISSUE TITLE
As a developer, I don't want to maintain a Docker development environment if it is unused

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#666]
## Notes
The project includes a Docker development environment that hasn't been used and I don't get the feeling that EBSS/FS will be using it either. This can be an unnecessary maintenance burden and takes up some time when running automated tests. Pending team discussion, I think we should remove the Docker development environment.

## Acceptance Criteria
- [x] The team understands that it is something that should or shouldn't be removed and is no longer necessary
- [x] There is no more Docker development environment
- [x] All documentation is updated
- [x] Remainder of development environment is unchanged
- [x] Remainder of CI functions is unchanged

## Tasks
- [x] Discuss as a team to determine if dropping this support is appropriate
- [x] Remove Docker related files in the application.
- [x] Remove `build-docker` step from CircleCI.
- [x] Leave other references to `docker` in CircleCI untouched as they are instructions for CircleCI.
- [x] Remove Docker related documentation in repo Readme and docs, and the project wiki
- [x] Remove Docker check from PR template
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- [] Usability tested
