### ISSUE TITLE
As a user, I need to be able to report and be notified about any bugs that I encounter, so that I can use an Open Forest application that works as it was intended. 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/fs-open-forest-platform#670]
## Notes
* During the 2018 pilot, the OPen Forest collected user feedback and learned about bug via an email address posted to the site. This solution is not sustainable. (a) it was a GSA email address, (2) It required members of the team to be on call to monitor and respond to emails, and (3) providing feedback to users re: the status of bug fixes was a manual process

## Acceptance Criteria
- [ ] Bug reporting system provides automated feedback to users 24/7
- [ ] Bug reporting 

## Tasks
- [ ] Model as-is bug-tracking workflow with swim lanes for end users, devs, and FS staff (if needed)
- [ ] Conduct user research to understand information needs around bug-tracking and response
- [ ] Design to-be workflow for proposed bug tracking system
- [ ] Validate design concept with users
- [ ] Consider conducting a comparative analysis of open source bug tracking tools that may facilitate to-be workflow 
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
@MelissaBraxton looks ok to me. Perhaps the team has a good understanding of a "bug" in this context, is there a need to define that? or would that be part of the "understand information needs around bug-tracking and response"?

**Comment by MelissaBraxton** [comment]
Good call, @ASprinkle. I've revised to make it clear that this is specific to bugs and is separate from the customer experience feedback tool in #617.

**Comment by lisamcmichael** [comment]
Met with @ASprinkle and compiled these next steps. Amber, take a look at the updates to tasks above, and make sure it looks good. Thx.

_Update Footer:_  
Change to: ”For help or technical questions:” (see Christmas Tree footer for guidance, and note this is separate from the Feedback Stories 776, 676)

Don’t want to mix in general feedback so,
remove GSA mailbox, and change to Shared mailbox

SM.FS.OpnFrstCsSup@usda.gov

Remove General Information ph# (because someone would not reach and “OF” person)
