### ISSUE TITLE
Add Brian Davidson and Abdul Qurashi as application admins in Dev and Staging

### ISSUE THREAD

**Issue by davemcorwin** [18F/fs-open-forest-platform#671]
## Notes
The engineering team should have access to act as an admin in development and staging environments.

For each name, an additional entry should be added to the `whitelist` in the credentials for the `eauth-service-provider` "user provided service" for `platform-dev` and `platform-staging` environments, Ex. 
```
{
  "name": "eauth-service-provider",
  "credentials": {
    ...
    "admin": [
      ...
      { "admin_username": "BRIAN_DAVIDSON", "forests": ["all"] },
      { "admin_username": "ABDUL_QURESHI", "forests": ["all"] }
    ]
  },
  ...
}
```

## Acceptance Criteria
- [x] @briandavidson has access to the admin area of Open Forest in `dev` and `staging` environments
- [x] @abdul1234e  has access to the admin area of Open Forest  in `dev` and `staging` environments

## Tasks
- [x] Add `BRIAN_DAVIDSON` to admin white list in `dev` and `staging`
- [x] Add `ABDUL_QURASHI` to admin white list in `dev` and `staging`
- []  CERT Eauth accounts are established
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [] Compare finished design with mockup
- [] Usability tested

**Comment by abdul1234e** [comment]
@ericsorenson @davemcorwin Updated Environment value in dev and staging.

**Comment by davemcorwin** [comment]
@ASprinkle The acceptance criteria here may have to change since while they have been whitelisted for access, they do not have CERT Eauth accounts so can't actually access those areas. Perhaps we need to create a separate issue to track that, and update this to be restricted to the whitelisting, then it will be complete.

**Comment by ASprinkle** [comment]
Updated the "Tasks" above to capture the additional work that is needed regarding eAuth CERT

**Comment by ASprinkle** [comment]
Approving based on information received from @abdul1234e "there is no code changes for updating those environment. Its .json file were i have already updated those with brian and myself credentials."
And at stand up this morning, we confirmed that @briandavidson and @abdul1234e have approrpriate access to dev and staging.

**Comment by ASprinkle** [comment]
@abdul1234e is there any more work that is needed on this? In other words, should this story be moved to Done, or Ready for Master?

**Comment by abdul1234e** [comment]
@ASprinkle yes, we can move it Done.
