### ISSUE TITLE
Upgrade ngx-md for snyk vulnerabilities 

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-open-forest-platform#680]
## Notes
upgrading ngx-md for snyk

## Acceptance Criteria
- [ ] ngx-md upgraded and passing snyk tests

## Tasks
- [ ] upgrade ngx-md to v8
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
cannot upgrade ngx-md unless we're on angular 8
