### ISSUE TITLE
As an OF team member, I want to know what the state regulations are for transporting Christmas trees so that I can plan my work. 

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#685]
## Notes
* What are things we should consider when making this story *

States have certain requirements for transporting forest products.  We should understand what those regulations are so that we can adjust our approach accordingly.

## Acceptance Criteria
- [x] We have an understanding of what the State of Washington requires when transporting Christmas trees
- [x] We have an understanding of what the State of Oregon requires when transporting Christmas trees
- [x] We can easily refer to the information
- [x] We have confirmed the information with the FS POC for at least two Forests in each State or a FS LE & I Captain from each State.

## Tasks
- [x] Research State of Oregon Forest Products Law
- [x] Research State of Washington Forest Products Law
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by DawnDesigner** [comment]
@ASprinkle  Please confirm that what I'm researching is what the regulations are for Christmas trees cut in Washington or Oregon and being transported into boarding states.  

**Oregon:** 
_What are the regulations for Christmas trees cut in Oregon and being transported into_:
1. Washington
2. Idaho
3. California
4. Nevada

**State of Washington** 
_What are the regulations for Christmas trees cut in Washington and being transported into:_
1. Canada
2. Idaho
3. Oregon

**Comment by ASprinkle** [comment]
@DawnDesigner 

What are the regulations for transporting a Christmas tree in
Oregon.
Washington.

For example: A state may require that the person transporting a Christmas tree has documentation or proof of permission from the landowner where they cut the tree from.  That documentation may or may not be required to be on the tree during transport.

We are not concerned at this point with regulations on transporting a tree from one state to another.

**Comment by carlsonem** [comment]
@DawnDesigner any update on this?

**Comment by DawnDesigner** [comment]
Here is the completed documentation/research on this effort:

**Conclusion:** 
Neither the state of Washington nor the state of Oregon have any requirements or restrictions if someone purchases a permit and cuts a tree on public lands/national forest lands - as long as they do not take that tree across any neighboring state lines. (see notes in document linked below for details on from who and how this information was gathered)

**Infestations**
Note: This is not the case if within any of those forests the trees have any kind of an outbreak or infestation. Since this is something that is constantly changing and most likely would affect the decision a National Forest representative would make regarding where individuals will be allowed to cut a  tree in a state, further investigation is suggested with the forest service staff to see if they restrict tree cutters from harvesting a Christmas tree in an infested area of the forest.
If they are not required to take that precaution, then it might be correct to post something like the following statement:

 “If you will be transporting your Christmas tree across any state line, please be sure to visit the  [National Plant Board Law and Regulations ](https://nationalplantboard.org/laws-and-regulations/)to see if there are any current outbreaks that might restrict a state from allowing a particular type of tree from entering into that boarding state.”

Full research document on Pinion: https://usfs.box.com/s/h13ilgrzfrqf944wxilieuqlygvczcwg

**Comment by DawnDesigner** [comment]
@ASprinkle I'm uploading the doc directly here as well as the link to Pinion above.

[Research- Washington-Oregon-Transport Within States (1).docx](https://github.com/18F/fs-open-forest-platform/files/3363735/Research-.Washington-Oregon-Transport.Within.States.1.docx)

In the folder on Pinion there are documents that support the findings for reference.

**Comment by ASprinkle** [comment]
I updated the research document that Dawn created with the confirmation I received from Forest LEO:
RCW 76.48.081 Specialized forest products permits—Expiration—Specifications. Where it does not describe any requirement to tag the Christmas tree. Also, follow up discussion with Mt. Hood and Gifford Pinchot Patrol Captain (who coordinated with LEO from the MBS and Oka-Wen):
Coriell, Andrew -FS 1:43 PM: 
James and I looked at RCW76.48.050 which we believe says that you dont need the tag attached to the tree. 
Sprinkle, Amber D -FS 1:43 PM: 
Ok, just a permission documentation - basically same as Oregon
Coriell, Andrew -FS 1:44 PM: 
Yes.   That is how we are reading it.   It excludes the tag requirement for special forest products / Christmas trees.
