### ISSUE TITLE
As an FS admin I would like to know that the Open Forest team is researching my forest's Christmas tree information as a page in Open Forest so that I can provide content review feedback.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#687]
## Notes
* What are things we should consider when making this story *

The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on a new forest's program
- [x] We are ready to input the content

## Tasks
- [x] Research forest Christmas tree content on their forest website
- [x] Save information in a location easy for the team to access
- [x] Find out if Amber has access to pull Forests Product Plans in TIM to research additional permit rules
- [x] PO approved

## New forests for Xmas trees
- [x] Deschutes National Forest
- [x] Gifford Pinchot National Forest
- [x] Fremont-Winema National Forest
- [x] Mt. Baker/Snoqualmie National Forest
- [x] Okanogan-Wenatchee National Forest
- [x] Rogue River-Siskiyou National Forest
- [x] Umatilla National Forest
- [x] Willamette National Forest

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by DawnDesigner** [comment]
@ASprinkle @lisaredux  I'd like to propose this workflow for this request for all forests coming up so identified SME's in the different forests can access the information easily to give edits and feedback for the content on the each forests page:

1.  I created a folder on Pinion here: https://usfs.box.com/s/g9a9ocnltsne5cxseqt8ci5navbwafwz - to share documents are we create them for individual Forests info sheets
2. I created a word document template drafted using the same content order on existing Xmas forest pages. We can use these for each forest identified as the next permit addition.  Template in the folder on Pinion here:  https://usfs.box.com/s/3fkq9se9jacw9riegjeboxv338evh9id - Labeled "All Forests Info Page Content"
3. Propose syntax for the name of the doc: **(Forest name)Forest Info Content (year)**
4.  When an individual forests info page is complete by UX with as much info as we are able to gather - we upload it to Pinion to this folder above ready for review and editing by you - Amber and the SME who is identified for that forest.

I also created links on the GITHUB info repository (Trello replacement) Wiki for you to easily access both the folder and the individual docs if that works instead of logging into Pinion (I think this works if you are logged in with you PIV card on a gov laptop when you click the link). We'll see - I had some trouble logging in through Firefox - but manually went to usda eauth, logged in and then was able to access everything.



This can replace Google doc sharing - Pinion allows doc sharing much like Google.

**Comment by lisaredux** [comment]
Thanks @DawnDesigner -- this workflow looks great and straightforward. I'll start another forest page and try to populate the information as I find it. Much appreciated that you got this started in an easy collaborative method and off Google.

**Comment by ASprinkle** [comment]
I plan to take a closer look at all of this today too!

**Comment by DawnDesigner** [comment]
I've completed the Deschutes forest detailed info page based on the template. (@ASprinkle I believe I may have deleted the page with your comments and don't see a way to bring it back. My apologies. Hoping the completed doc below will have covered any changes or suggestions.)

As a standard for this process I suggest the UX designer who is researching the information create a folder on Pinion in the Content folder with the name of the forest, in the folder place the Word doc that has all the text, and a folder with the images and provide links to those items for the SME's from the different forests to review and suggest changes, and eventually for the developers as a resource to create the page after the story is moved to ready.

For the Deschutes here is the link to the shared doc:
 https://usfs.box.com/s/5dpkbeyyznwxg5fwbyb2soctkw6kivei

Images folder: 
https://usfs.box.com/s/1daczyoxopmr3so9kc9tpuis8alk44hm

**Comment by ASprinkle** [comment]
Thanks I updated it with comments that I think will be helpful as we do the same for other forests.

**Comment by ASprinkle** [comment]
After our stand up/retro/planning session this morning, and after meeting with Lisa. I have created this as an epic, and each forest to be added has it's own story connected to this epic. Those stories have been prioritized in the Backlog.

**Comment by lisamcmichael** [comment]
After reviewing it with Amber, the Gifford Pinchot Forest Research Documentation is ready for developer. 
[Gifford Pinchot Forest Info 2019 v3.docx](https://github.com/18F/fs-open-forest-platform/files/3383888/Gifford.Pinchot.Forest.Info.2019.v3.docx)

**Comment by lisamcmichael** [comment]
See #700: research documentation Fremont-Winema National Forest @ASprinkle

**Comment by ASprinkle** [comment]
All of the initially researched content for these stories is housed in Pinyon in the folder that Dawn originally created. https://usfs.box.com/s/g9a9ocnltsne5cxseqt8ci5navbwafwz
