### ISSUE TITLE
As a developer I want to test so that I know that the new ‘purchaseDate’ field is working through testing.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#698]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] we know that the tests we are running are working/testing the thing we want to test.

## Tasks
- [x] Refactoring some of the tests to cover the new ‘purchaseDate’ field.
- [x] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by ASprinkle** [comment]
This story is connected to #550 @briandavidson

**Comment by briandavidson** [comment]
@ASprinkle is this issue for addressing test coverage on the new purchaseDate field?

**Comment by ASprinkle** [comment]
Yes. I believe you and Dave talked about it, and the suggestion was to create a story for it rather than address it as a task within #550.

**Comment by briandavidson** [comment]
@ASprinkle yup! Just wanted to confirm. Would it be alright if I renamed the title of this card to something like "the 'purchaseDate' field should have test coverage"?

**Comment by carlsonem** [comment]
@briandavidson any update on this?

**Comment by briandavidson** [comment]
@carlsonem shooting to have this complete by EOD today.

**Comment by briandavidson** [comment]
@ASprinkle this can be closed -- the updates to the tests that I did in #550 adequately cover the `purchaseDate` field.

**Comment by ASprinkle** [comment]
@briandavidson I'll move it to done to capture this Sprints work, then we'll close the issue at the beginning of next sprint, along with the others.
