### ISSUE TITLE
As an FS admin I want the Open Forest team to research the Gifford Pinchot Forest's Christmas tree program information so that I can do a content review later.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#699]
## Notes
* What are things we should consider when making this story *

The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on the Gifford Pinchot's Christmas tree program
- [x] We have enough information to create a new issue for the Dev team to develop the content on Open Forest, in preparation for forest review's and content feedback.

## Tasks
- [x] Research the Gifford Pinchot's Christmas tree content on their forest website, following the existing Open Forest workflow.
             - [ ] Content gathered for: season dates, pricing, maximum number of permits, tree height, stump height, prohibited actions/areas/tree species, cutting area information/maps, and Forest offices contact information, 
- [x] Save the information in a location easy for the team to access (pinyon)
- [x] PO reviewed/edited 
- [x] PO approved

## Definition of Done
- [x] Acceptance criteria is met

**Comment by ASprinkle** [comment]
Note from Lisa: After reviewing it with Amber, the Gifford Pinchot Forest Research Documentation is ready for developer.
Gifford Pinchot Forest Info 2019 v3.docx

**Comment by lisamcmichael** [comment]
After reviewing it with Amber, the Gifford Pinchot Forest Research Documentation is ready for developer.
[Gifford Pinchot Forest Info 2019 v3.docx](https://github.com/18F/fs-open-forest-platform/files/3386425/Gifford.Pinchot.Forest.Info.2019.v3.docx)

**Comment by ASprinkle** [comment]
We should make sure we have a smooth hand off to Dev for this - see story #721
