### ISSUE TITLE
As an FS admin I want the Open Forest team to research the Fremont-Winema Forest's Christmas tree program information so that I can do a content review later.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#700]
## Notes
The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on the Fremont-Winema's Christmas tree program
- [x] We have enough information to create a new issue for the Dev team to develop the content on Open Forest, in preparation for forest review's and content feedback.

## Tasks
- [x] Research the Fremont-Winema's Christmas tree content on their forest website, following the existing Open Forest workflow.
             - [ ] Content gathered for: season dates, pricing, maximum number of permits, tree height, stump height, prohibited actions/areas/tree species, cutting area information/maps, and Forest offices contact information, 
- [x] Save the information in a location easy for the team to access (pinyon)
- [x] PO reviewed/edited 
- [x] PO approved

## Definition of Done
- [ ] Acceptance criteria is met

**Comment by lisamcmichael** [comment]
Research documentation ready for review @ASprinkle 
[Fremont-Winema Forest Info 2019 v1.docx](https://github.com/18F/fs-open-forest-platform/files/3386750/Fremont-Winema.Forest.Info.2019.v1.docx)

**Comment by ASprinkle** [comment]
@lisamcmichael 
[DRAFT FT2 Results Briefing for RF Version 2.docx](https://github.com/18F/fs-open-forest-platform/files/3387071/DRAFT.FT2.Results.Briefing.for.RF.Version.2.docx)

**Comment by aaronburk** [comment]
Lisa does not yet have access to Zenhub

**Comment by ASprinkle** [comment]
@lisamcmichael I realized I had attached the wrong word document a few days ago (a result of multiple work priorities)... So i updated the above link with v2 of the Fre-Win doc.  Thanks!

**Comment by lisamcmichael** [comment]
I am still running into issues with access to "Programs/Github" to make changes. For now, here is the updated version 2.1, and any follow-ups with POC are in Version History for traceability.
