### ISSUE TITLE
As an FS admin I want the Open Forest team to research the Mt. Baker Snoqualmie Forest's Christmas tree program information so that I can do a content review later.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#701]
## Notes
The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on the Mt. Baker Snoqualmie's Christmas tree program
- [x] We have enough information to create a new issue for the Dev team to develop the content on Open Forest, in preparation for forest review's and content feedback.

## Tasks
- [x] Research the Mt. Baker Snoqualmie Christmas tree content on their forest website, following the existing Open Forest workflow.
             - [ ] Content gathered for: season dates, pricing, maximum number of permits, tree height, stump height, prohibited actions/areas/tree species, cutting area information/maps, and Forest offices contact information, 
- [x] Save the information in a location easy for the team to access (pinyon)
- [x] PO reviewed/edited 
- [x] PO approved

## Definition of Done
- [x] Acceptance criteria is met

**Comment by lisamcmichael** [comment]
@ASprinkle and @carlsonem 

Ready for Amber to review version 1. 

Eric - should I be able to move files out of Backlog? Thx!

[https://app.zenhub.com/files/88538878/2537d2de-d66b-4d55-a27c-ab2b30b3395e/download](https://app.zenhub.com/files/88538878/2537d2de-d66b-4d55-a27c-ab2b30b3395e/download)

**Comment by ASprinkle** [comment]
[Mt. Baker Snoqualmie Forest Info 2019 v1.docx](https://github.com/18F/fs-open-forest-platform/files/3398020/Mt.Baker.Snoqualmie.Forest.Info.2019.v1.docx)

**Comment by ASprinkle** [comment]
@lisamcmichael  Can you take a look at v2 attached. I added more links that might be helpful

[Mt. Baker Snoqualmie Forest Info 2019 v2.docx](https://github.com/18F/fs-open-forest-platform/files/3398293/Mt.Baker.Snoqualmie.Forest.Info.2019.v2.docx)

**Comment by ASprinkle** [comment]
@lisamcmichael looks great. Thank you! 
[Mt.Baker.Snoqualmie.Forest.Info.2019.v3 (1).docx](https://github.com/18F/fs-open-forest-platform/files/3404326/Mt.Baker.Snoqualmie.Forest.Info.2019.v3.1.docx)
