### ISSUE TITLE
As an FS admin I want the Open Forest team to research the Okanogan-Wenatchee Forest's Christmas tree program information so that I can do a content review later.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#702]
## Notes
The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on the Okanogan-Wenatchee's Christmas tree program
- [x] We have enough information to create a new issue for the Dev team to develop the content on Open Forest, in preparation for forest review's and content feedback.

## Tasks
- [x] Research the Okanogan-Wenatchee's Christmas tree content on their forest website, following the existing Open Forest workflow.
             - [ ] Content gathered for: season dates, pricing, maximum number of permits, tree height, stump height, prohibited actions/areas/tree species, cutting area information/maps, and Forest offices contact information, 
- [x] Save the information in a location easy for the team to access (pinyon)
- [x] PO reviewed/edited 
- [x] PO approved

## Definition of Done
- [x] Acceptance criteria is met

**Comment by lisamcmichael** [comment]
@amber - V1 ready for review

@carlsonem - ready to move out of backlog; assumption: no longer a blocker

[https://app.zenhub.com/files/88538878/92b21e93-ebcb-4d4a-8a82-e9df8609e8d7/download](https://app.zenhub.com/files/88538878/92b21e93-ebcb-4d4a-8a82-e9df8609e8d7/download)

**Comment by ASprinkle** [comment]
@lisamcmichael @carlsonem  I moved it from the backlog into "in progress".

A story is essentially a blocker until it is PO Approved and moved to "Done", or until the blocking task has been completed.

**Comment by lisamcmichael** [comment]
Amber: the link is here. If there is an issue with it, just let me know. 

https://app.zenhub.com/files/88538878/92b21e93-ebcb-4d4a-8a82-e9df8609e8d7/download

**Comment by ASprinkle** [comment]
[Okanogan-Wenatchee Forest Info 2019 v1.docx](https://github.com/18F/fs-open-forest-platform/files/3398016/Okanogan-Wenatchee.Forest.Info.2019.v1.docx)

**Comment by ASprinkle** [comment]
[Okanogan-Wenatchee Forest Info 2019 v2.docx](https://github.com/18F/fs-open-forest-platform/files/3398333/Okanogan-Wenatchee.Forest.Info.2019.v2.docx)

**Comment by lisamcmichael** [comment]
@amber @carlsonem 

Amber - v3 is ready for review. Thx!
[Okanogan-Wenatchee.Forest.Info.2019.v3.docx](https://github.com/18F/fs-open-forest-platform/files/3402182/Okanogan-Wenatchee.Forest.Info.2019.v3.docx)

**Comment by ASprinkle** [comment]
Looks great. I made one tweak and saved final v4 here. Thanks @lisamcmichael 
[Okanogan-Wenatchee.Forest.Info.2019.v4.docx](https://github.com/18F/fs-open-forest-platform/files/3404318/Okanogan-Wenatchee.Forest.Info.2019.v4.docx)
