### ISSUE TITLE
As an FS admin I want the Open Forest team to research the Rogue River-Siskiyou Forest's Christmas tree program information so that I can do a content review later.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#703]
## Notes
The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on the Rogue River-Siskiyou's Christmas tree program
- [x] We have enough information to create a new issue for the Dev team to develop the content on Open Forest, in preparation for forest review's and content feedback.

## Tasks
- [x] Research the Rogue River Siskiyou's Christmas tree content on their forest website, following the existing Open Forest workflow.
             - [ ] Content gathered for: season dates, pricing, maximum number of permits, tree height, stump height, prohibited actions/areas/tree species, cutting area information/maps, and Forest offices contact information, 
- [x] Save the information in a location easy for the team to access (pinyon)
- [x] PO reviewed/edited 
- [x] PO approved

## Definition of Done
- [x] Acceptance criteria is met

**Comment by lisamcmichael** [comment]
[https://app.zenhub.com/files/88538878/d50b411a-73eb-490a-9f6b-0bffe2642982/download]

**Comment by lisamcmichael** [comment]
[Rogue River-Siskiyou Forest Info 2019 v3.docx](https://github.com/18F/fs-open-forest-platform/files/3412293/Rogue.River-Siskiyou.Forest.Info.2019.v3.docx)
