### ISSUE TITLE
As an FS admin I want the Open Forest team to research the Umatilla Forest's Christmas tree program information so that I can do a content review later.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#704]
## Notes
The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on the Umatilla's Christmas tree program
- [x] We have enough information to create a new issue for the Dev team to develop the content on Open Forest, in preparation for forest review's and content feedback.

## Tasks
- [x] Research the Umatilla's Christmas tree content on their forest website, following the existing Open Forest workflow.
             - [ ] Content gathered for: season dates, pricing, maximum number of permits, tree height, stump height, prohibited actions/areas/tree species, cutting area information/maps, and Forest offices contact information, 
- [x] Save the information in a location easy for the team to access (pinyon)
- [x] PO reviewed/edited 
- [x] PO approved

## Definition of Done
- [ ] Acceptance criteria is met

**Comment by ASprinkle** [comment]
[Umatilla Forest Info 2019 v2.docx](https://github.com/18F/fs-open-forest-platform/files/3422944/Umatilla.Forest.Info.2019.v2.docx)

**Comment by lisamcmichael** [comment]
@carlsonem @ASprinkle @lisaredux 
[Umatilla Forest Info 2019 v2.1.docx](https://github.com/18F/fs-open-forest-platform/files/3423421/Umatilla.Forest.Info.2019.v2.1.docx)

**Comment by carlsonem** [comment]
@ASprinkle Please review and let us know if this is ready for the developers to start to work on

**Comment by ASprinkle** [comment]
@carlsonem @lisamcmichael  reviewed v2.1 - looks good to me!
