### ISSUE TITLE
As an FS admin I want the Open Forest team to research the Willamette's Christmas tree program information so that I can do a content review later.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#705]
## Notes
The Open Forest team would research and gather Christmas tree program content and information to populate new pages in Open Forest, so that a new forest's POC can have something to review and provide feedback on the content being drafted.

## Acceptance Criteria
- [x] We have gathered information on the Willamette's Christmas tree program
- [x] We have enough information to create a new issue for the Dev team to develop the content on Open Forest, in preparation for forest review's and content feedback.

## Tasks
- [x] Research the Willamette's Christmas tree content on their forest website, following the existing Open Forest workflow.
             - [ ] Content gathered for: season dates, pricing, maximum number of permits, tree height, stump height, prohibited actions/areas/tree species, cutting area information/maps, and Forest offices contact information, 
- [x] Save the information in a location easy for the team to access (pinyon)
- [x] PO reviewed/edited 
- [x] PO approved

## Definition of Done
- [ ] Acceptance criteria is met

**Comment by lisamcmichael** [comment]
@carlsonem I sent Amber #705 this morning.

**Comment by lisamcmichael** [comment]
[Willamette Forest Info 2019 v2.docx](https://github.com/18F/fs-open-forest-platform/files/3412298/Willamette.Forest.Info.2019.v2.docx)
