### ISSUE TITLE
Validation test from OpenForest dev to sudsws database

### ISSUE THREAD

**Issue by mwreiss** [18F/fs-open-forest-platform#708]
Note: Verify that OpenForest data queries to sudsws are displaying as expected.  The sudsws went through a 12c upgrade last week, the NRM team requested an internal test from OF dev.  Report findings/results back to Xin Feng.

## Acceptance Criteria
- [] OpenForest Dev and Staging environments have the expected results from the sudsws database.

## Tasks
- [] Verify that OpenForest dev is getting back expected results from sudsws database
- [] Coordinate and communicate with the NRM dev (Xin Feng) team on test results
- [] Test performance and response from the sudsws database

## Done
- [] Test results are as expected from the OpenForest dev platform
- [] Performance is reporting as expected

**Comment by mwreiss** [comment]
closed>redundant issue on program board
