### ISSUE TITLE
As an OF team member I would like to know who I can work with at each new R6 pilot forest so that I can be sure about how I am building the site

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#714]
## Notes
we need to have POC identified for each of the new pilot forests so that we can ensure the content is accurate and the process reflects the forests needs.

## Acceptance Criteria
- [x] We know who the new forest POCs are

## Tasks
We have POC identified for the following forests
- [x] Deschutes National Forest
- [x] Gifford Pinchot National Forest
- [x] Fremont-Winema National Forest
- [x] Mt. Baker/Snoqualmie National Forest
- [x] Okanogan-Wenatchee National Forest
- [x] Rogue River-Siskiyou National Forest
- [x] Umatilla National Forest
- [x] Willamette National Forest
- [x] PO approved

## Definition of Done
- [x] Tasks completed

**Comment by ASprinkle** [comment]
POC list is in the Open Forest file in Pinyon https://usfs.box.com/s/iu1pyn8mjyaahi1ifxhx1ihih0m72nms

**Comment by ASprinkle** [comment]
@aaronburk we received at least one name from each new R6 pilot forest for our POC.
