### ISSUE TITLE
Remove Ron Sharpe from Snyk security reports

### ISSUE THREAD

**Issue by mwreiss** [18F/fs-open-forest-platform#732]
## Notes
_After doing an account audit and review, the removal of Ron Sharpe is needed in the auto-generated snyk security reports. Ron has been assigned to other duties and will not be focusing on Open Forest.

## Acceptance Criteria
- [x] @mreiss , @jlerner and @aqureshi review that Ron's account has been deleted fully from the snyk reports.

## Tasks
- [x] @abdul will update snyk environment variables to remove Ron from receiving reports.
- [x] PO Approved

## Account to remove
- [x] Remove ronald.sharpe@usda.gov and or ronald.sharpe@fs.fed.us

**Comment by abdul1234e** [comment]
I don't see Ronald id in snyk members.

**Comment by abdul1234e** [comment]
"port": 25,
      "security": [
        "SM.FS.OpenFrstOps@usda.gov",
        "ronald.sharpe@usda.gov",
        "hieunguyen@fs.fed.us"

Hie is already in the list and i will update and remove Ronald from the Snyk list.

**Comment by mwreiss** [comment]
Verified Ron Sharpe is removed.
