### ISSUE TITLE
Verify/add Hieu to snyk security reports

### ISSUE THREAD

**Issue by mwreiss** [18F/fs-open-forest-platform#733]
## Notes
_Please add Hieu Nguyen to the auto-generated snyk security reports. 

## Acceptance Criteria
- [] @mreiss , @jlerner and @aqureshi review that Hieu's account has been added  to the snyk reports.

## Tasks
- [] @abdul will update snyk environment to add/verify Hieu can recieve snyk reports.
- [x] PO Approved

## Account to add/verify
- [x] Add/verify hieu.nguyen@usda.gov account is in place to receive reports.

**Comment by abdul1234e** [comment]
Verified Hieu is already in the list for getting nightly snyk reports.

**Comment by mwreiss** [comment]
Issue: csv file is getting to large and failing to email report.  @abdul1234e looking into resolution.

**Comment by ASprinkle** [comment]
@mwreiss  was the issue referenced ^ resolved?
