### ISSUE TITLE
As a FS visitor to the production site, I want to view Open Forest in IE without issues so that I don't have to install Chrome.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#735]
## Notes
* What are things we should consider when making this story *

## Acceptance Criteria
- [x] FS can view Open Forest production site (public facing) in IE without issues.

## Tasks
- [x] Troubleshoot with dev team
- [x] PO approved

## Definition of Done
- [ ] AC met, documented in comments.

**Comment by ASprinkle** [comment]
Amber and FS admins have been having issues accessing the public facing prod site through IE.  

Resolution:  Remove usda.gov from "Compatibility View" setting, and refresh page.

![image](https://user-images.githubusercontent.com/33435621/61403246-bf00d700-a889-11e9-84ed-d14d699eb82d.png)
![image](https://user-images.githubusercontent.com/33435621/61403256-c3c58b00-a889-11e9-9cbd-320e25e358fb.png)
