### ISSUE TITLE
Integrate the Open Forest admin portal with FS Apps to enable more secure login for FS users

### ISSUE THREAD

**Issue by carlsonem** [18F/fs-open-forest-platform#756]
## Acceptance Criteria
- [ ] An admin user can login to Open Forest via FSApps

## Tasks
- [ ] Hold a kickoff with FSApps Team
- [ ] FS Apps Team Adds Open Forest to their platform
- [ ] Open Forest team updates code so admin users can login to application via FSApps, via eAuth
- [ ] User testing
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
