### ISSUE TITLE
Re-instate Google Chrome Latest

### ISSUE THREAD

**Issue by mtlaney** [18F/fs-open-forest-platform#768]
## Notes
Revert to issue #767 once Protractor and Selenium testing suites have been updated to allow newest version of Google Chrome within CircleCI

## Acceptance Criteria
- [ ] Add Install Latest Chrome to circleci - config.yml
- [ ] All tests are correctly passing again

## Tasks
- [ ] Add Install Latest Chrome to circleci - config.yml
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
