### ISSUE TITLE
As a customer for the Umatilla NF, I would like to view the Contact Us information on the Open Forest site without having to select a link so that I can have the information easily.

### ISSUE THREAD

**Issue by ASprinkle** [18F/fs-open-forest-platform#787]
## Notes
* What are things we should consider when making this story *

The Umatilla NF is the only one with links in the Contact Us section.
Let's update this so the experience is consistent between forests:
![image.png](https://images.zenhubusercontent.com/5a00e34b8a75884b90864b6f/576f38fc-c48d-4610-8747-6246991102e8)

## Acceptance Criteria
- [ ] The Contact Us information for the Umatilla is provided on the information page
- [ ] The information follows the same layout format as the other forests.

## Tasks
- [ ] Obtain contact us information for the Umatilla
- [ ] Update content
- [ ] PO approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested
